// Code generated by protoc-gen-go. DO NOT EDIT.
// source: econ_gcmessages.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package protobuf is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package protobuf to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EGCItemMsg int32

const (
	EGCItemMsg_k_EMsgGCBase                                 EGCItemMsg = 1000
	EGCItemMsg_k_EMsgGCSetItemPosition                      EGCItemMsg = 1001
	EGCItemMsg_k_EMsgGCCraft                                EGCItemMsg = 1002
	EGCItemMsg_k_EMsgGCCraftResponse                        EGCItemMsg = 1003
	EGCItemMsg_k_EMsgGCDelete                               EGCItemMsg = 1004
	EGCItemMsg_k_EMsgGCVerifyCacheSubscription              EGCItemMsg = 1005
	EGCItemMsg_k_EMsgGCNameItem                             EGCItemMsg = 1006
	EGCItemMsg_k_EMsgGCUnlockCrate                          EGCItemMsg = 1007
	EGCItemMsg_k_EMsgGCUnlockCrateResponse                  EGCItemMsg = 1008
	EGCItemMsg_k_EMsgGCPaintItem                            EGCItemMsg = 1009
	EGCItemMsg_k_EMsgGCPaintItemResponse                    EGCItemMsg = 1010
	EGCItemMsg_k_EMsgGCGoldenWrenchBroadcast                EGCItemMsg = 1011
	EGCItemMsg_k_EMsgGCMOTDRequest                          EGCItemMsg = 1012
	EGCItemMsg_k_EMsgGCMOTDRequestResponse                  EGCItemMsg = 1013
	EGCItemMsg_k_EMsgGCAddItemToSocket_DEPRECATED           EGCItemMsg = 1014
	EGCItemMsg_k_EMsgGCAddItemToSocketResponse_DEPRECATED   EGCItemMsg = 1015
	EGCItemMsg_k_EMsgGCAddSocketToBaseItem_DEPRECATED       EGCItemMsg = 1016
	EGCItemMsg_k_EMsgGCAddSocketToItem_DEPRECATED           EGCItemMsg = 1017
	EGCItemMsg_k_EMsgGCAddSocketToItemResponse_DEPRECATED   EGCItemMsg = 1018
	EGCItemMsg_k_EMsgGCNameBaseItem                         EGCItemMsg = 1019
	EGCItemMsg_k_EMsgGCNameBaseItemResponse                 EGCItemMsg = 1020
	EGCItemMsg_k_EMsgGCRemoveSocketItem_DEPRECATED          EGCItemMsg = 1021
	EGCItemMsg_k_EMsgGCRemoveSocketItemResponse_DEPRECATED  EGCItemMsg = 1022
	EGCItemMsg_k_EMsgGCCustomizeItemTexture                 EGCItemMsg = 1023
	EGCItemMsg_k_EMsgGCCustomizeItemTextureResponse         EGCItemMsg = 1024
	EGCItemMsg_k_EMsgGCUseItemRequest                       EGCItemMsg = 1025
	EGCItemMsg_k_EMsgGCUseItemResponse                      EGCItemMsg = 1026
	EGCItemMsg_k_EMsgGCGiftedItems_DEPRECATED               EGCItemMsg = 1027
	EGCItemMsg_k_EMsgGCRemoveItemName                       EGCItemMsg = 1030
	EGCItemMsg_k_EMsgGCRemoveItemPaint                      EGCItemMsg = 1031
	EGCItemMsg_k_EMsgGCGiftWrapItem                         EGCItemMsg = 1032
	EGCItemMsg_k_EMsgGCGiftWrapItemResponse                 EGCItemMsg = 1033
	EGCItemMsg_k_EMsgGCDeliverGift                          EGCItemMsg = 1034
	EGCItemMsg_k_EMsgGCDeliverGiftResponseGiver             EGCItemMsg = 1035
	EGCItemMsg_k_EMsgGCDeliverGiftResponseReceiver          EGCItemMsg = 1036
	EGCItemMsg_k_EMsgGCUnwrapGiftRequest                    EGCItemMsg = 1037
	EGCItemMsg_k_EMsgGCUnwrapGiftResponse                   EGCItemMsg = 1038
	EGCItemMsg_k_EMsgGCSetItemStyle                         EGCItemMsg = 1039
	EGCItemMsg_k_EMsgGCUsedClaimCodeItem                    EGCItemMsg = 1040
	EGCItemMsg_k_EMsgGCSortItems                            EGCItemMsg = 1041
	EGCItemMsg_k_EMsgGC_RevolvingLootList_DEPRECATED        EGCItemMsg = 1042
	EGCItemMsg_k_EMsgGCLookupAccount                        EGCItemMsg = 1043
	EGCItemMsg_k_EMsgGCLookupAccountResponse                EGCItemMsg = 1044
	EGCItemMsg_k_EMsgGCLookupAccountName                    EGCItemMsg = 1045
	EGCItemMsg_k_EMsgGCLookupAccountNameResponse            EGCItemMsg = 1046
	EGCItemMsg_k_EMsgGCUpdateItemSchema                     EGCItemMsg = 1049
	EGCItemMsg_k_EMsgGCRemoveCustomTexture                  EGCItemMsg = 1051
	EGCItemMsg_k_EMsgGCRemoveCustomTextureResponse          EGCItemMsg = 1052
	EGCItemMsg_k_EMsgGCRemoveMakersMark                     EGCItemMsg = 1053
	EGCItemMsg_k_EMsgGCRemoveMakersMarkResponse             EGCItemMsg = 1054
	EGCItemMsg_k_EMsgGCRemoveUniqueCraftIndex               EGCItemMsg = 1055
	EGCItemMsg_k_EMsgGCRemoveUniqueCraftIndexResponse       EGCItemMsg = 1056
	EGCItemMsg_k_EMsgGCSaxxyBroadcast                       EGCItemMsg = 1057
	EGCItemMsg_k_EMsgGCBackpackSortFinished                 EGCItemMsg = 1058
	EGCItemMsg_k_EMsgGCAdjustItemEquippedState              EGCItemMsg = 1059
	EGCItemMsg_k_EMsgGCCollectItem                          EGCItemMsg = 1061
	EGCItemMsg_k_EMsgGCItemAcknowledged__DEPRECATED         EGCItemMsg = 1062
	EGCItemMsg_k_EMsgGC_ReportAbuse                         EGCItemMsg = 1065
	EGCItemMsg_k_EMsgGC_ReportAbuseResponse                 EGCItemMsg = 1066
	EGCItemMsg_k_EMsgGCNameItemNotification                 EGCItemMsg = 1068
	EGCItemMsg_k_EMsgGCApplyConsumableEffects               EGCItemMsg = 1069
	EGCItemMsg_k_EMsgGCConsumableExhausted                  EGCItemMsg = 1070
	EGCItemMsg_k_EMsgGCShowItemsPickedUp                    EGCItemMsg = 1071
	EGCItemMsg_k_EMsgGCClientDisplayNotification            EGCItemMsg = 1072
	EGCItemMsg_k_EMsgGCApplyStrangePart                     EGCItemMsg = 1073
	EGCItemMsg_k_EMsgGC_IncrementKillCountAttribute         EGCItemMsg = 1074
	EGCItemMsg_k_EMsgGC_IncrementKillCountResponse          EGCItemMsg = 1075
	EGCItemMsg_k_EMsgGCApplyPennantUpgrade                  EGCItemMsg = 1076
	EGCItemMsg_k_EMsgGCSetItemPositions                     EGCItemMsg = 1077
	EGCItemMsg_k_EMsgGCApplyEggEssence                      EGCItemMsg = 1078
	EGCItemMsg_k_EMsgGCNameEggEssenceResponse               EGCItemMsg = 1079
	EGCItemMsg_k_EMsgGCPaintKitItem                         EGCItemMsg = 1080
	EGCItemMsg_k_EMsgGCPaintKitBaseItem                     EGCItemMsg = 1081
	EGCItemMsg_k_EMsgGCPaintKitItemResponse                 EGCItemMsg = 1082
	EGCItemMsg_k_EMsgGCGiftedItems                          EGCItemMsg = 1083
	EGCItemMsg_k_EMsgGCUnlockItemStyle                      EGCItemMsg = 1084
	EGCItemMsg_k_EMsgGCUnlockItemStyleResponse              EGCItemMsg = 1085
	EGCItemMsg_k_EMsgGCApplySticker                         EGCItemMsg = 1086
	EGCItemMsg_k_EMsgGCItemAcknowledged                     EGCItemMsg = 1087
	EGCItemMsg_k_EMsgGCStatTrakSwap                         EGCItemMsg = 1088
	EGCItemMsg_k_EMsgGCUserTrackTimePlayedConsecutively     EGCItemMsg = 1089
	EGCItemMsg_k_EMsgGCItemCustomizationNotification        EGCItemMsg = 1090
	EGCItemMsg_k_EMsgGCModifyItemAttribute                  EGCItemMsg = 1091
	EGCItemMsg_k_EMsgGCCasketItemAdd                        EGCItemMsg = 1092
	EGCItemMsg_k_EMsgGCCasketItemExtract                    EGCItemMsg = 1093
	EGCItemMsg_k_EMsgGCCasketItemLoadContents               EGCItemMsg = 1094
	EGCItemMsg_k_EMsgGCTradingBase                          EGCItemMsg = 1500
	EGCItemMsg_k_EMsgGCTrading_InitiateTradeRequest         EGCItemMsg = 1501
	EGCItemMsg_k_EMsgGCTrading_InitiateTradeResponse        EGCItemMsg = 1502
	EGCItemMsg_k_EMsgGCTrading_StartSession                 EGCItemMsg = 1503
	EGCItemMsg_k_EMsgGCTrading_SetItem                      EGCItemMsg = 1504
	EGCItemMsg_k_EMsgGCTrading_RemoveItem                   EGCItemMsg = 1505
	EGCItemMsg_k_EMsgGCTrading_UpdateTradeInfo              EGCItemMsg = 1506
	EGCItemMsg_k_EMsgGCTrading_SetReadiness                 EGCItemMsg = 1507
	EGCItemMsg_k_EMsgGCTrading_ReadinessResponse            EGCItemMsg = 1508
	EGCItemMsg_k_EMsgGCTrading_SessionClosed                EGCItemMsg = 1509
	EGCItemMsg_k_EMsgGCTrading_CancelSession                EGCItemMsg = 1510
	EGCItemMsg_k_EMsgGCTrading_TradeChatMsg                 EGCItemMsg = 1511
	EGCItemMsg_k_EMsgGCTrading_ConfirmOffer                 EGCItemMsg = 1512
	EGCItemMsg_k_EMsgGCTrading_TradeTypingChatMsg           EGCItemMsg = 1513
	EGCItemMsg_k_EMsgGCServerBrowser_FavoriteServer         EGCItemMsg = 1601
	EGCItemMsg_k_EMsgGCServerBrowser_BlacklistServer        EGCItemMsg = 1602
	EGCItemMsg_k_EMsgGCServerRentalsBase                    EGCItemMsg = 1700
	EGCItemMsg_k_EMsgGCItemPreviewCheckStatus               EGCItemMsg = 1701
	EGCItemMsg_k_EMsgGCItemPreviewStatusResponse            EGCItemMsg = 1702
	EGCItemMsg_k_EMsgGCItemPreviewRequest                   EGCItemMsg = 1703
	EGCItemMsg_k_EMsgGCItemPreviewRequestResponse           EGCItemMsg = 1704
	EGCItemMsg_k_EMsgGCItemPreviewExpire                    EGCItemMsg = 1705
	EGCItemMsg_k_EMsgGCItemPreviewExpireNotification        EGCItemMsg = 1706
	EGCItemMsg_k_EMsgGCItemPreviewItemBoughtNotification    EGCItemMsg = 1707
	EGCItemMsg_k_EMsgGCDev_NewItemRequest                   EGCItemMsg = 2001
	EGCItemMsg_k_EMsgGCDev_NewItemRequestResponse           EGCItemMsg = 2002
	EGCItemMsg_k_EMsgGCDev_PaintKitDropItem                 EGCItemMsg = 2003
	EGCItemMsg_k_EMsgGCStoreGetUserData                     EGCItemMsg = 2500
	EGCItemMsg_k_EMsgGCStoreGetUserDataResponse             EGCItemMsg = 2501
	EGCItemMsg_k_EMsgGCStorePurchaseInit_DEPRECATED         EGCItemMsg = 2502
	EGCItemMsg_k_EMsgGCStorePurchaseInitResponse_DEPRECATED EGCItemMsg = 2503
	EGCItemMsg_k_EMsgGCStorePurchaseFinalize                EGCItemMsg = 2504
	EGCItemMsg_k_EMsgGCStorePurchaseFinalizeResponse        EGCItemMsg = 2505
	EGCItemMsg_k_EMsgGCStorePurchaseCancel                  EGCItemMsg = 2506
	EGCItemMsg_k_EMsgGCStorePurchaseCancelResponse          EGCItemMsg = 2507
	EGCItemMsg_k_EMsgGCStorePurchaseQueryTxn                EGCItemMsg = 2508
	EGCItemMsg_k_EMsgGCStorePurchaseQueryTxnResponse        EGCItemMsg = 2509
	EGCItemMsg_k_EMsgGCStorePurchaseInit                    EGCItemMsg = 2510
	EGCItemMsg_k_EMsgGCStorePurchaseInitResponse            EGCItemMsg = 2511
	EGCItemMsg_k_EMsgGCBannedWordListRequest                EGCItemMsg = 2512
	EGCItemMsg_k_EMsgGCBannedWordListResponse               EGCItemMsg = 2513
	EGCItemMsg_k_EMsgGCToGCBannedWordListBroadcast          EGCItemMsg = 2514
	EGCItemMsg_k_EMsgGCToGCBannedWordListUpdated            EGCItemMsg = 2515
	EGCItemMsg_k_EMsgGCToGCDirtySDOCache                    EGCItemMsg = 2516
	EGCItemMsg_k_EMsgGCToGCDirtyMultipleSDOCache            EGCItemMsg = 2517
	EGCItemMsg_k_EMsgGCToGCUpdateSQLKeyValue                EGCItemMsg = 2518
	EGCItemMsg_k_EMsgGCToGCIsTrustedServer                  EGCItemMsg = 2519
	EGCItemMsg_k_EMsgGCToGCIsTrustedServerResponse          EGCItemMsg = 2520
	EGCItemMsg_k_EMsgGCToGCBroadcastConsoleCommand          EGCItemMsg = 2521
	EGCItemMsg_k_EMsgGCServerVersionUpdated                 EGCItemMsg = 2522
	EGCItemMsg_k_EMsgGCApplyAutograph                       EGCItemMsg = 2523
	EGCItemMsg_k_EMsgGCToGCWebAPIAccountChanged             EGCItemMsg = 2524
	EGCItemMsg_k_EMsgGCRequestAnnouncements                 EGCItemMsg = 2525
	EGCItemMsg_k_EMsgGCRequestAnnouncementsResponse         EGCItemMsg = 2526
	EGCItemMsg_k_EMsgGCRequestPassportItemGrant             EGCItemMsg = 2527
	EGCItemMsg_k_EMsgGCClientVersionUpdated                 EGCItemMsg = 2528
	EGCItemMsg_k_EMsgGCAdjustItemEquippedStateMulti         EGCItemMsg = 2529
	EGCItemMsg_k_EMsgGCRecurringSubscriptionStatus          EGCItemMsg = 2530
)

var EGCItemMsg_name = map[int32]string{
	1000: "k_EMsgGCBase",
	1001: "k_EMsgGCSetItemPosition",
	1002: "k_EMsgGCCraft",
	1003: "k_EMsgGCCraftResponse",
	1004: "k_EMsgGCDelete",
	1005: "k_EMsgGCVerifyCacheSubscription",
	1006: "k_EMsgGCNameItem",
	1007: "k_EMsgGCUnlockCrate",
	1008: "k_EMsgGCUnlockCrateResponse",
	1009: "k_EMsgGCPaintItem",
	1010: "k_EMsgGCPaintItemResponse",
	1011: "k_EMsgGCGoldenWrenchBroadcast",
	1012: "k_EMsgGCMOTDRequest",
	1013: "k_EMsgGCMOTDRequestResponse",
	1014: "k_EMsgGCAddItemToSocket_DEPRECATED",
	1015: "k_EMsgGCAddItemToSocketResponse_DEPRECATED",
	1016: "k_EMsgGCAddSocketToBaseItem_DEPRECATED",
	1017: "k_EMsgGCAddSocketToItem_DEPRECATED",
	1018: "k_EMsgGCAddSocketToItemResponse_DEPRECATED",
	1019: "k_EMsgGCNameBaseItem",
	1020: "k_EMsgGCNameBaseItemResponse",
	1021: "k_EMsgGCRemoveSocketItem_DEPRECATED",
	1022: "k_EMsgGCRemoveSocketItemResponse_DEPRECATED",
	1023: "k_EMsgGCCustomizeItemTexture",
	1024: "k_EMsgGCCustomizeItemTextureResponse",
	1025: "k_EMsgGCUseItemRequest",
	1026: "k_EMsgGCUseItemResponse",
	1027: "k_EMsgGCGiftedItems_DEPRECATED",
	1030: "k_EMsgGCRemoveItemName",
	1031: "k_EMsgGCRemoveItemPaint",
	1032: "k_EMsgGCGiftWrapItem",
	1033: "k_EMsgGCGiftWrapItemResponse",
	1034: "k_EMsgGCDeliverGift",
	1035: "k_EMsgGCDeliverGiftResponseGiver",
	1036: "k_EMsgGCDeliverGiftResponseReceiver",
	1037: "k_EMsgGCUnwrapGiftRequest",
	1038: "k_EMsgGCUnwrapGiftResponse",
	1039: "k_EMsgGCSetItemStyle",
	1040: "k_EMsgGCUsedClaimCodeItem",
	1041: "k_EMsgGCSortItems",
	1042: "k_EMsgGC_RevolvingLootList_DEPRECATED",
	1043: "k_EMsgGCLookupAccount",
	1044: "k_EMsgGCLookupAccountResponse",
	1045: "k_EMsgGCLookupAccountName",
	1046: "k_EMsgGCLookupAccountNameResponse",
	1049: "k_EMsgGCUpdateItemSchema",
	1051: "k_EMsgGCRemoveCustomTexture",
	1052: "k_EMsgGCRemoveCustomTextureResponse",
	1053: "k_EMsgGCRemoveMakersMark",
	1054: "k_EMsgGCRemoveMakersMarkResponse",
	1055: "k_EMsgGCRemoveUniqueCraftIndex",
	1056: "k_EMsgGCRemoveUniqueCraftIndexResponse",
	1057: "k_EMsgGCSaxxyBroadcast",
	1058: "k_EMsgGCBackpackSortFinished",
	1059: "k_EMsgGCAdjustItemEquippedState",
	1061: "k_EMsgGCCollectItem",
	1062: "k_EMsgGCItemAcknowledged__DEPRECATED",
	1065: "k_EMsgGC_ReportAbuse",
	1066: "k_EMsgGC_ReportAbuseResponse",
	1068: "k_EMsgGCNameItemNotification",
	1069: "k_EMsgGCApplyConsumableEffects",
	1070: "k_EMsgGCConsumableExhausted",
	1071: "k_EMsgGCShowItemsPickedUp",
	1072: "k_EMsgGCClientDisplayNotification",
	1073: "k_EMsgGCApplyStrangePart",
	1074: "k_EMsgGC_IncrementKillCountAttribute",
	1075: "k_EMsgGC_IncrementKillCountResponse",
	1076: "k_EMsgGCApplyPennantUpgrade",
	1077: "k_EMsgGCSetItemPositions",
	1078: "k_EMsgGCApplyEggEssence",
	1079: "k_EMsgGCNameEggEssenceResponse",
	1080: "k_EMsgGCPaintKitItem",
	1081: "k_EMsgGCPaintKitBaseItem",
	1082: "k_EMsgGCPaintKitItemResponse",
	1083: "k_EMsgGCGiftedItems",
	1084: "k_EMsgGCUnlockItemStyle",
	1085: "k_EMsgGCUnlockItemStyleResponse",
	1086: "k_EMsgGCApplySticker",
	1087: "k_EMsgGCItemAcknowledged",
	1088: "k_EMsgGCStatTrakSwap",
	1089: "k_EMsgGCUserTrackTimePlayedConsecutively",
	1090: "k_EMsgGCItemCustomizationNotification",
	1091: "k_EMsgGCModifyItemAttribute",
	1092: "k_EMsgGCCasketItemAdd",
	1093: "k_EMsgGCCasketItemExtract",
	1094: "k_EMsgGCCasketItemLoadContents",
	1500: "k_EMsgGCTradingBase",
	1501: "k_EMsgGCTrading_InitiateTradeRequest",
	1502: "k_EMsgGCTrading_InitiateTradeResponse",
	1503: "k_EMsgGCTrading_StartSession",
	1504: "k_EMsgGCTrading_SetItem",
	1505: "k_EMsgGCTrading_RemoveItem",
	1506: "k_EMsgGCTrading_UpdateTradeInfo",
	1507: "k_EMsgGCTrading_SetReadiness",
	1508: "k_EMsgGCTrading_ReadinessResponse",
	1509: "k_EMsgGCTrading_SessionClosed",
	1510: "k_EMsgGCTrading_CancelSession",
	1511: "k_EMsgGCTrading_TradeChatMsg",
	1512: "k_EMsgGCTrading_ConfirmOffer",
	1513: "k_EMsgGCTrading_TradeTypingChatMsg",
	1601: "k_EMsgGCServerBrowser_FavoriteServer",
	1602: "k_EMsgGCServerBrowser_BlacklistServer",
	1700: "k_EMsgGCServerRentalsBase",
	1701: "k_EMsgGCItemPreviewCheckStatus",
	1702: "k_EMsgGCItemPreviewStatusResponse",
	1703: "k_EMsgGCItemPreviewRequest",
	1704: "k_EMsgGCItemPreviewRequestResponse",
	1705: "k_EMsgGCItemPreviewExpire",
	1706: "k_EMsgGCItemPreviewExpireNotification",
	1707: "k_EMsgGCItemPreviewItemBoughtNotification",
	2001: "k_EMsgGCDev_NewItemRequest",
	2002: "k_EMsgGCDev_NewItemRequestResponse",
	2003: "k_EMsgGCDev_PaintKitDropItem",
	2500: "k_EMsgGCStoreGetUserData",
	2501: "k_EMsgGCStoreGetUserDataResponse",
	2502: "k_EMsgGCStorePurchaseInit_DEPRECATED",
	2503: "k_EMsgGCStorePurchaseInitResponse_DEPRECATED",
	2504: "k_EMsgGCStorePurchaseFinalize",
	2505: "k_EMsgGCStorePurchaseFinalizeResponse",
	2506: "k_EMsgGCStorePurchaseCancel",
	2507: "k_EMsgGCStorePurchaseCancelResponse",
	2508: "k_EMsgGCStorePurchaseQueryTxn",
	2509: "k_EMsgGCStorePurchaseQueryTxnResponse",
	2510: "k_EMsgGCStorePurchaseInit",
	2511: "k_EMsgGCStorePurchaseInitResponse",
	2512: "k_EMsgGCBannedWordListRequest",
	2513: "k_EMsgGCBannedWordListResponse",
	2514: "k_EMsgGCToGCBannedWordListBroadcast",
	2515: "k_EMsgGCToGCBannedWordListUpdated",
	2516: "k_EMsgGCToGCDirtySDOCache",
	2517: "k_EMsgGCToGCDirtyMultipleSDOCache",
	2518: "k_EMsgGCToGCUpdateSQLKeyValue",
	2519: "k_EMsgGCToGCIsTrustedServer",
	2520: "k_EMsgGCToGCIsTrustedServerResponse",
	2521: "k_EMsgGCToGCBroadcastConsoleCommand",
	2522: "k_EMsgGCServerVersionUpdated",
	2523: "k_EMsgGCApplyAutograph",
	2524: "k_EMsgGCToGCWebAPIAccountChanged",
	2525: "k_EMsgGCRequestAnnouncements",
	2526: "k_EMsgGCRequestAnnouncementsResponse",
	2527: "k_EMsgGCRequestPassportItemGrant",
	2528: "k_EMsgGCClientVersionUpdated",
	2529: "k_EMsgGCAdjustItemEquippedStateMulti",
	2530: "k_EMsgGCRecurringSubscriptionStatus",
}

var EGCItemMsg_value = map[string]int32{
	"k_EMsgGCBase":                                 1000,
	"k_EMsgGCSetItemPosition":                      1001,
	"k_EMsgGCCraft":                                1002,
	"k_EMsgGCCraftResponse":                        1003,
	"k_EMsgGCDelete":                               1004,
	"k_EMsgGCVerifyCacheSubscription":              1005,
	"k_EMsgGCNameItem":                             1006,
	"k_EMsgGCUnlockCrate":                          1007,
	"k_EMsgGCUnlockCrateResponse":                  1008,
	"k_EMsgGCPaintItem":                            1009,
	"k_EMsgGCPaintItemResponse":                    1010,
	"k_EMsgGCGoldenWrenchBroadcast":                1011,
	"k_EMsgGCMOTDRequest":                          1012,
	"k_EMsgGCMOTDRequestResponse":                  1013,
	"k_EMsgGCAddItemToSocket_DEPRECATED":           1014,
	"k_EMsgGCAddItemToSocketResponse_DEPRECATED":   1015,
	"k_EMsgGCAddSocketToBaseItem_DEPRECATED":       1016,
	"k_EMsgGCAddSocketToItem_DEPRECATED":           1017,
	"k_EMsgGCAddSocketToItemResponse_DEPRECATED":   1018,
	"k_EMsgGCNameBaseItem":                         1019,
	"k_EMsgGCNameBaseItemResponse":                 1020,
	"k_EMsgGCRemoveSocketItem_DEPRECATED":          1021,
	"k_EMsgGCRemoveSocketItemResponse_DEPRECATED":  1022,
	"k_EMsgGCCustomizeItemTexture":                 1023,
	"k_EMsgGCCustomizeItemTextureResponse":         1024,
	"k_EMsgGCUseItemRequest":                       1025,
	"k_EMsgGCUseItemResponse":                      1026,
	"k_EMsgGCGiftedItems_DEPRECATED":               1027,
	"k_EMsgGCRemoveItemName":                       1030,
	"k_EMsgGCRemoveItemPaint":                      1031,
	"k_EMsgGCGiftWrapItem":                         1032,
	"k_EMsgGCGiftWrapItemResponse":                 1033,
	"k_EMsgGCDeliverGift":                          1034,
	"k_EMsgGCDeliverGiftResponseGiver":             1035,
	"k_EMsgGCDeliverGiftResponseReceiver":          1036,
	"k_EMsgGCUnwrapGiftRequest":                    1037,
	"k_EMsgGCUnwrapGiftResponse":                   1038,
	"k_EMsgGCSetItemStyle":                         1039,
	"k_EMsgGCUsedClaimCodeItem":                    1040,
	"k_EMsgGCSortItems":                            1041,
	"k_EMsgGC_RevolvingLootList_DEPRECATED":        1042,
	"k_EMsgGCLookupAccount":                        1043,
	"k_EMsgGCLookupAccountResponse":                1044,
	"k_EMsgGCLookupAccountName":                    1045,
	"k_EMsgGCLookupAccountNameResponse":            1046,
	"k_EMsgGCUpdateItemSchema":                     1049,
	"k_EMsgGCRemoveCustomTexture":                  1051,
	"k_EMsgGCRemoveCustomTextureResponse":          1052,
	"k_EMsgGCRemoveMakersMark":                     1053,
	"k_EMsgGCRemoveMakersMarkResponse":             1054,
	"k_EMsgGCRemoveUniqueCraftIndex":               1055,
	"k_EMsgGCRemoveUniqueCraftIndexResponse":       1056,
	"k_EMsgGCSaxxyBroadcast":                       1057,
	"k_EMsgGCBackpackSortFinished":                 1058,
	"k_EMsgGCAdjustItemEquippedState":              1059,
	"k_EMsgGCCollectItem":                          1061,
	"k_EMsgGCItemAcknowledged__DEPRECATED":         1062,
	"k_EMsgGC_ReportAbuse":                         1065,
	"k_EMsgGC_ReportAbuseResponse":                 1066,
	"k_EMsgGCNameItemNotification":                 1068,
	"k_EMsgGCApplyConsumableEffects":               1069,
	"k_EMsgGCConsumableExhausted":                  1070,
	"k_EMsgGCShowItemsPickedUp":                    1071,
	"k_EMsgGCClientDisplayNotification":            1072,
	"k_EMsgGCApplyStrangePart":                     1073,
	"k_EMsgGC_IncrementKillCountAttribute":         1074,
	"k_EMsgGC_IncrementKillCountResponse":          1075,
	"k_EMsgGCApplyPennantUpgrade":                  1076,
	"k_EMsgGCSetItemPositions":                     1077,
	"k_EMsgGCApplyEggEssence":                      1078,
	"k_EMsgGCNameEggEssenceResponse":               1079,
	"k_EMsgGCPaintKitItem":                         1080,
	"k_EMsgGCPaintKitBaseItem":                     1081,
	"k_EMsgGCPaintKitItemResponse":                 1082,
	"k_EMsgGCGiftedItems":                          1083,
	"k_EMsgGCUnlockItemStyle":                      1084,
	"k_EMsgGCUnlockItemStyleResponse":              1085,
	"k_EMsgGCApplySticker":                         1086,
	"k_EMsgGCItemAcknowledged":                     1087,
	"k_EMsgGCStatTrakSwap":                         1088,
	"k_EMsgGCUserTrackTimePlayedConsecutively":     1089,
	"k_EMsgGCItemCustomizationNotification":        1090,
	"k_EMsgGCModifyItemAttribute":                  1091,
	"k_EMsgGCCasketItemAdd":                        1092,
	"k_EMsgGCCasketItemExtract":                    1093,
	"k_EMsgGCCasketItemLoadContents":               1094,
	"k_EMsgGCTradingBase":                          1500,
	"k_EMsgGCTrading_InitiateTradeRequest":         1501,
	"k_EMsgGCTrading_InitiateTradeResponse":        1502,
	"k_EMsgGCTrading_StartSession":                 1503,
	"k_EMsgGCTrading_SetItem":                      1504,
	"k_EMsgGCTrading_RemoveItem":                   1505,
	"k_EMsgGCTrading_UpdateTradeInfo":              1506,
	"k_EMsgGCTrading_SetReadiness":                 1507,
	"k_EMsgGCTrading_ReadinessResponse":            1508,
	"k_EMsgGCTrading_SessionClosed":                1509,
	"k_EMsgGCTrading_CancelSession":                1510,
	"k_EMsgGCTrading_TradeChatMsg":                 1511,
	"k_EMsgGCTrading_ConfirmOffer":                 1512,
	"k_EMsgGCTrading_TradeTypingChatMsg":           1513,
	"k_EMsgGCServerBrowser_FavoriteServer":         1601,
	"k_EMsgGCServerBrowser_BlacklistServer":        1602,
	"k_EMsgGCServerRentalsBase":                    1700,
	"k_EMsgGCItemPreviewCheckStatus":               1701,
	"k_EMsgGCItemPreviewStatusResponse":            1702,
	"k_EMsgGCItemPreviewRequest":                   1703,
	"k_EMsgGCItemPreviewRequestResponse":           1704,
	"k_EMsgGCItemPreviewExpire":                    1705,
	"k_EMsgGCItemPreviewExpireNotification":        1706,
	"k_EMsgGCItemPreviewItemBoughtNotification":    1707,
	"k_EMsgGCDev_NewItemRequest":                   2001,
	"k_EMsgGCDev_NewItemRequestResponse":           2002,
	"k_EMsgGCDev_PaintKitDropItem":                 2003,
	"k_EMsgGCStoreGetUserData":                     2500,
	"k_EMsgGCStoreGetUserDataResponse":             2501,
	"k_EMsgGCStorePurchaseInit_DEPRECATED":         2502,
	"k_EMsgGCStorePurchaseInitResponse_DEPRECATED": 2503,
	"k_EMsgGCStorePurchaseFinalize":                2504,
	"k_EMsgGCStorePurchaseFinalizeResponse":        2505,
	"k_EMsgGCStorePurchaseCancel":                  2506,
	"k_EMsgGCStorePurchaseCancelResponse":          2507,
	"k_EMsgGCStorePurchaseQueryTxn":                2508,
	"k_EMsgGCStorePurchaseQueryTxnResponse":        2509,
	"k_EMsgGCStorePurchaseInit":                    2510,
	"k_EMsgGCStorePurchaseInitResponse":            2511,
	"k_EMsgGCBannedWordListRequest":                2512,
	"k_EMsgGCBannedWordListResponse":               2513,
	"k_EMsgGCToGCBannedWordListBroadcast":          2514,
	"k_EMsgGCToGCBannedWordListUpdated":            2515,
	"k_EMsgGCToGCDirtySDOCache":                    2516,
	"k_EMsgGCToGCDirtyMultipleSDOCache":            2517,
	"k_EMsgGCToGCUpdateSQLKeyValue":                2518,
	"k_EMsgGCToGCIsTrustedServer":                  2519,
	"k_EMsgGCToGCIsTrustedServerResponse":          2520,
	"k_EMsgGCToGCBroadcastConsoleCommand":          2521,
	"k_EMsgGCServerVersionUpdated":                 2522,
	"k_EMsgGCApplyAutograph":                       2523,
	"k_EMsgGCToGCWebAPIAccountChanged":             2524,
	"k_EMsgGCRequestAnnouncements":                 2525,
	"k_EMsgGCRequestAnnouncementsResponse":         2526,
	"k_EMsgGCRequestPassportItemGrant":             2527,
	"k_EMsgGCClientVersionUpdated":                 2528,
	"k_EMsgGCAdjustItemEquippedStateMulti":         2529,
	"k_EMsgGCRecurringSubscriptionStatus":          2530,
}

func (x EGCItemMsg) Enum() *EGCItemMsg {
	p := new(EGCItemMsg)
	*p = x
	return p
}

func (x EGCItemMsg) String() string {
	return proto.EnumName(EGCItemMsg_name, int32(x))
}

func (x *EGCItemMsg) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EGCItemMsg_value, data, "EGCItemMsg")
	if err != nil {
		return err
	}
	*x = EGCItemMsg(value)
	return nil
}

func (EGCItemMsg) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_123d8ffb2ecfd02d, []int{0}
}

type EGCMsgResponse int32

const (
	EGCMsgResponse_k_EGCMsgResponseOK           EGCMsgResponse = 0
	EGCMsgResponse_k_EGCMsgResponseDenied       EGCMsgResponse = 1
	EGCMsgResponse_k_EGCMsgResponseServerError  EGCMsgResponse = 2
	EGCMsgResponse_k_EGCMsgResponseTimeout      EGCMsgResponse = 3
	EGCMsgResponse_k_EGCMsgResponseInvalid      EGCMsgResponse = 4
	EGCMsgResponse_k_EGCMsgResponseNoMatch      EGCMsgResponse = 5
	EGCMsgResponse_k_EGCMsgResponseUnknownError EGCMsgResponse = 6
	EGCMsgResponse_k_EGCMsgResponseNotLoggedOn  EGCMsgResponse = 7
	EGCMsgResponse_k_EGCMsgFailedToCreate       EGCMsgResponse = 8
	EGCMsgResponse_k_EGCMsgLimitExceeded        EGCMsgResponse = 9
	EGCMsgResponse_k_EGCMsgCommitUnfinalized    EGCMsgResponse = 10
)

var EGCMsgResponse_name = map[int32]string{
	0:  "k_EGCMsgResponseOK",
	1:  "k_EGCMsgResponseDenied",
	2:  "k_EGCMsgResponseServerError",
	3:  "k_EGCMsgResponseTimeout",
	4:  "k_EGCMsgResponseInvalid",
	5:  "k_EGCMsgResponseNoMatch",
	6:  "k_EGCMsgResponseUnknownError",
	7:  "k_EGCMsgResponseNotLoggedOn",
	8:  "k_EGCMsgFailedToCreate",
	9:  "k_EGCMsgLimitExceeded",
	10: "k_EGCMsgCommitUnfinalized",
}

var EGCMsgResponse_value = map[string]int32{
	"k_EGCMsgResponseOK":           0,
	"k_EGCMsgResponseDenied":       1,
	"k_EGCMsgResponseServerError":  2,
	"k_EGCMsgResponseTimeout":      3,
	"k_EGCMsgResponseInvalid":      4,
	"k_EGCMsgResponseNoMatch":      5,
	"k_EGCMsgResponseUnknownError": 6,
	"k_EGCMsgResponseNotLoggedOn":  7,
	"k_EGCMsgFailedToCreate":       8,
	"k_EGCMsgLimitExceeded":        9,
	"k_EGCMsgCommitUnfinalized":    10,
}

func (x EGCMsgResponse) Enum() *EGCMsgResponse {
	p := new(EGCMsgResponse)
	*p = x
	return p
}

func (x EGCMsgResponse) String() string {
	return proto.EnumName(EGCMsgResponse_name, int32(x))
}

func (x *EGCMsgResponse) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EGCMsgResponse_value, data, "EGCMsgResponse")
	if err != nil {
		return err
	}
	*x = EGCMsgResponse(value)
	return nil
}

func (EGCMsgResponse) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_123d8ffb2ecfd02d, []int{1}
}

type EUnlockStyle int32

const (
	EUnlockStyle_k_UnlockStyle_Succeeded               EUnlockStyle = 0
	EUnlockStyle_k_UnlockStyle_Failed_PreReq           EUnlockStyle = 1
	EUnlockStyle_k_UnlockStyle_Failed_CantAfford       EUnlockStyle = 2
	EUnlockStyle_k_UnlockStyle_Failed_CantCommit       EUnlockStyle = 3
	EUnlockStyle_k_UnlockStyle_Failed_CantLockCache    EUnlockStyle = 4
	EUnlockStyle_k_UnlockStyle_Failed_CantAffordAttrib EUnlockStyle = 5
)

var EUnlockStyle_name = map[int32]string{
	0: "k_UnlockStyle_Succeeded",
	1: "k_UnlockStyle_Failed_PreReq",
	2: "k_UnlockStyle_Failed_CantAfford",
	3: "k_UnlockStyle_Failed_CantCommit",
	4: "k_UnlockStyle_Failed_CantLockCache",
	5: "k_UnlockStyle_Failed_CantAffordAttrib",
}

var EUnlockStyle_value = map[string]int32{
	"k_UnlockStyle_Succeeded":               0,
	"k_UnlockStyle_Failed_PreReq":           1,
	"k_UnlockStyle_Failed_CantAfford":       2,
	"k_UnlockStyle_Failed_CantCommit":       3,
	"k_UnlockStyle_Failed_CantLockCache":    4,
	"k_UnlockStyle_Failed_CantAffordAttrib": 5,
}

func (x EUnlockStyle) Enum() *EUnlockStyle {
	p := new(EUnlockStyle)
	*p = x
	return p
}

func (x EUnlockStyle) String() string {
	return proto.EnumName(EUnlockStyle_name, int32(x))
}

func (x *EUnlockStyle) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EUnlockStyle_value, data, "EUnlockStyle")
	if err != nil {
		return err
	}
	*x = EUnlockStyle(value)
	return nil
}

func (EUnlockStyle) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_123d8ffb2ecfd02d, []int{2}
}

type EGCItemCustomizationNotification int32

const (
	EGCItemCustomizationNotification_k_EGCItemCustomizationNotification_NameItem                  EGCItemCustomizationNotification = 1006
	EGCItemCustomizationNotification_k_EGCItemCustomizationNotification_UnlockCrate               EGCItemCustomizationNotification = 1007
	EGCItemCustomizationNotification_k_EGCItemCustomizationNotification_XRayItemReveal            EGCItemCustomizationNotification = 1008
	EGCItemCustomizationNotification_k_EGCItemCustomizationNotification_XRayItemClaim             EGCItemCustomizationNotification = 1009
	EGCItemCustomizationNotification_k_EGCItemCustomizationNotification_CasketTooFull             EGCItemCustomizationNotification = 1011
	EGCItemCustomizationNotification_k_EGCItemCustomizationNotification_CasketContents            EGCItemCustomizationNotification = 1012
	EGCItemCustomizationNotification_k_EGCItemCustomizationNotification_CasketAdded               EGCItemCustomizationNotification = 1013
	EGCItemCustomizationNotification_k_EGCItemCustomizationNotification_CasketRemoved             EGCItemCustomizationNotification = 1014
	EGCItemCustomizationNotification_k_EGCItemCustomizationNotification_CasketInvFull             EGCItemCustomizationNotification = 1015
	EGCItemCustomizationNotification_k_EGCItemCustomizationNotification_NameBaseItem              EGCItemCustomizationNotification = 1019
	EGCItemCustomizationNotification_k_EGCItemCustomizationNotification_RemoveItemName            EGCItemCustomizationNotification = 1030
	EGCItemCustomizationNotification_k_EGCItemCustomizationNotification_RemoveSticker             EGCItemCustomizationNotification = 1053
	EGCItemCustomizationNotification_k_EGCItemCustomizationNotification_ApplySticker              EGCItemCustomizationNotification = 1086
	EGCItemCustomizationNotification_k_EGCItemCustomizationNotification_StatTrakSwap              EGCItemCustomizationNotification = 1088
	EGCItemCustomizationNotification_k_EGCItemCustomizationNotification_RemovePatch               EGCItemCustomizationNotification = 1089
	EGCItemCustomizationNotification_k_EGCItemCustomizationNotification_ApplyPatch                EGCItemCustomizationNotification = 1090
	EGCItemCustomizationNotification_k_EGCItemCustomizationNotification_ActivateFanToken          EGCItemCustomizationNotification = 9178
	EGCItemCustomizationNotification_k_EGCItemCustomizationNotification_ActivateOperationCoin     EGCItemCustomizationNotification = 9179
	EGCItemCustomizationNotification_k_EGCItemCustomizationNotification_GraffitiUnseal            EGCItemCustomizationNotification = 9185
	EGCItemCustomizationNotification_k_EGCItemCustomizationNotification_GenerateSouvenir          EGCItemCustomizationNotification = 9204
	EGCItemCustomizationNotification_k_EGCItemCustomizationNotification_ClientRedeemMissionReward EGCItemCustomizationNotification = 9209
)

var EGCItemCustomizationNotification_name = map[int32]string{
	1006: "k_EGCItemCustomizationNotification_NameItem",
	1007: "k_EGCItemCustomizationNotification_UnlockCrate",
	1008: "k_EGCItemCustomizationNotification_XRayItemReveal",
	1009: "k_EGCItemCustomizationNotification_XRayItemClaim",
	1011: "k_EGCItemCustomizationNotification_CasketTooFull",
	1012: "k_EGCItemCustomizationNotification_CasketContents",
	1013: "k_EGCItemCustomizationNotification_CasketAdded",
	1014: "k_EGCItemCustomizationNotification_CasketRemoved",
	1015: "k_EGCItemCustomizationNotification_CasketInvFull",
	1019: "k_EGCItemCustomizationNotification_NameBaseItem",
	1030: "k_EGCItemCustomizationNotification_RemoveItemName",
	1053: "k_EGCItemCustomizationNotification_RemoveSticker",
	1086: "k_EGCItemCustomizationNotification_ApplySticker",
	1088: "k_EGCItemCustomizationNotification_StatTrakSwap",
	1089: "k_EGCItemCustomizationNotification_RemovePatch",
	1090: "k_EGCItemCustomizationNotification_ApplyPatch",
	9178: "k_EGCItemCustomizationNotification_ActivateFanToken",
	9179: "k_EGCItemCustomizationNotification_ActivateOperationCoin",
	9185: "k_EGCItemCustomizationNotification_GraffitiUnseal",
	9204: "k_EGCItemCustomizationNotification_GenerateSouvenir",
	9209: "k_EGCItemCustomizationNotification_ClientRedeemMissionReward",
}

var EGCItemCustomizationNotification_value = map[string]int32{
	"k_EGCItemCustomizationNotification_NameItem":                  1006,
	"k_EGCItemCustomizationNotification_UnlockCrate":               1007,
	"k_EGCItemCustomizationNotification_XRayItemReveal":            1008,
	"k_EGCItemCustomizationNotification_XRayItemClaim":             1009,
	"k_EGCItemCustomizationNotification_CasketTooFull":             1011,
	"k_EGCItemCustomizationNotification_CasketContents":            1012,
	"k_EGCItemCustomizationNotification_CasketAdded":               1013,
	"k_EGCItemCustomizationNotification_CasketRemoved":             1014,
	"k_EGCItemCustomizationNotification_CasketInvFull":             1015,
	"k_EGCItemCustomizationNotification_NameBaseItem":              1019,
	"k_EGCItemCustomizationNotification_RemoveItemName":            1030,
	"k_EGCItemCustomizationNotification_RemoveSticker":             1053,
	"k_EGCItemCustomizationNotification_ApplySticker":              1086,
	"k_EGCItemCustomizationNotification_StatTrakSwap":              1088,
	"k_EGCItemCustomizationNotification_RemovePatch":               1089,
	"k_EGCItemCustomizationNotification_ApplyPatch":                1090,
	"k_EGCItemCustomizationNotification_ActivateFanToken":          9178,
	"k_EGCItemCustomizationNotification_ActivateOperationCoin":     9179,
	"k_EGCItemCustomizationNotification_GraffitiUnseal":            9185,
	"k_EGCItemCustomizationNotification_GenerateSouvenir":          9204,
	"k_EGCItemCustomizationNotification_ClientRedeemMissionReward": 9209,
}

func (x EGCItemCustomizationNotification) Enum() *EGCItemCustomizationNotification {
	p := new(EGCItemCustomizationNotification)
	*p = x
	return p
}

func (x EGCItemCustomizationNotification) String() string {
	return proto.EnumName(EGCItemCustomizationNotification_name, int32(x))
}

func (x *EGCItemCustomizationNotification) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EGCItemCustomizationNotification_value, data, "EGCItemCustomizationNotification")
	if err != nil {
		return err
	}
	*x = EGCItemCustomizationNotification(value)
	return nil
}

func (EGCItemCustomizationNotification) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_123d8ffb2ecfd02d, []int{3}
}

type CMsgGCGiftedItems struct {
	Accountid             *uint32  `protobuf:"varint,1,opt,name=accountid" json:"accountid,omitempty"`
	Giftdefindex          *uint32  `protobuf:"varint,2,opt,name=giftdefindex" json:"giftdefindex,omitempty"`
	MaxGiftsPossible      *uint32  `protobuf:"varint,3,opt,name=max_gifts_possible,json=maxGiftsPossible" json:"max_gifts_possible,omitempty"`
	NumEligibleRecipients *uint32  `protobuf:"varint,4,opt,name=num_eligible_recipients,json=numEligibleRecipients" json:"num_eligible_recipients,omitempty"`
	RecipientsAccountids  []uint32 `protobuf:"varint,5,rep,name=recipients_accountids,json=recipientsAccountids" json:"recipients_accountids,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *CMsgGCGiftedItems) Reset()         { *m = CMsgGCGiftedItems{} }
func (m *CMsgGCGiftedItems) String() string { return proto.CompactTextString(m) }
func (*CMsgGCGiftedItems) ProtoMessage()    {}
func (*CMsgGCGiftedItems) Descriptor() ([]byte, []int) {
	return fileDescriptor_123d8ffb2ecfd02d, []int{0}
}

func (m *CMsgGCGiftedItems) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgGCGiftedItems.Unmarshal(m, b)
}
func (m *CMsgGCGiftedItems) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgGCGiftedItems.Marshal(b, m, deterministic)
}
func (m *CMsgGCGiftedItems) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgGCGiftedItems.Merge(m, src)
}
func (m *CMsgGCGiftedItems) XXX_Size() int {
	return xxx_messageInfo_CMsgGCGiftedItems.Size(m)
}
func (m *CMsgGCGiftedItems) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgGCGiftedItems.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgGCGiftedItems proto.InternalMessageInfo

func (m *CMsgGCGiftedItems) GetAccountid() uint32 {
	if m != nil && m.Accountid != nil {
		return *m.Accountid
	}
	return 0
}

func (m *CMsgGCGiftedItems) GetGiftdefindex() uint32 {
	if m != nil && m.Giftdefindex != nil {
		return *m.Giftdefindex
	}
	return 0
}

func (m *CMsgGCGiftedItems) GetMaxGiftsPossible() uint32 {
	if m != nil && m.MaxGiftsPossible != nil {
		return *m.MaxGiftsPossible
	}
	return 0
}

func (m *CMsgGCGiftedItems) GetNumEligibleRecipients() uint32 {
	if m != nil && m.NumEligibleRecipients != nil {
		return *m.NumEligibleRecipients
	}
	return 0
}

func (m *CMsgGCGiftedItems) GetRecipientsAccountids() []uint32 {
	if m != nil {
		return m.RecipientsAccountids
	}
	return nil
}

type CMsgApplyAutograph struct {
	AutographItemId      *uint64  `protobuf:"varint,1,opt,name=autograph_item_id,json=autographItemId" json:"autograph_item_id,omitempty"`
	ItemItemId           *uint64  `protobuf:"varint,2,opt,name=item_item_id,json=itemItemId" json:"item_item_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgApplyAutograph) Reset()         { *m = CMsgApplyAutograph{} }
func (m *CMsgApplyAutograph) String() string { return proto.CompactTextString(m) }
func (*CMsgApplyAutograph) ProtoMessage()    {}
func (*CMsgApplyAutograph) Descriptor() ([]byte, []int) {
	return fileDescriptor_123d8ffb2ecfd02d, []int{1}
}

func (m *CMsgApplyAutograph) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgApplyAutograph.Unmarshal(m, b)
}
func (m *CMsgApplyAutograph) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgApplyAutograph.Marshal(b, m, deterministic)
}
func (m *CMsgApplyAutograph) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgApplyAutograph.Merge(m, src)
}
func (m *CMsgApplyAutograph) XXX_Size() int {
	return xxx_messageInfo_CMsgApplyAutograph.Size(m)
}
func (m *CMsgApplyAutograph) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgApplyAutograph.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgApplyAutograph proto.InternalMessageInfo

func (m *CMsgApplyAutograph) GetAutographItemId() uint64 {
	if m != nil && m.AutographItemId != nil {
		return *m.AutographItemId
	}
	return 0
}

func (m *CMsgApplyAutograph) GetItemItemId() uint64 {
	if m != nil && m.ItemItemId != nil {
		return *m.ItemItemId
	}
	return 0
}

type CMsgCasketItem struct {
	CasketItemId         *uint64  `protobuf:"varint,1,opt,name=casket_item_id,json=casketItemId" json:"casket_item_id,omitempty"`
	ItemItemId           *uint64  `protobuf:"varint,2,opt,name=item_item_id,json=itemItemId" json:"item_item_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgCasketItem) Reset()         { *m = CMsgCasketItem{} }
func (m *CMsgCasketItem) String() string { return proto.CompactTextString(m) }
func (*CMsgCasketItem) ProtoMessage()    {}
func (*CMsgCasketItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_123d8ffb2ecfd02d, []int{2}
}

func (m *CMsgCasketItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgCasketItem.Unmarshal(m, b)
}
func (m *CMsgCasketItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgCasketItem.Marshal(b, m, deterministic)
}
func (m *CMsgCasketItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgCasketItem.Merge(m, src)
}
func (m *CMsgCasketItem) XXX_Size() int {
	return xxx_messageInfo_CMsgCasketItem.Size(m)
}
func (m *CMsgCasketItem) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgCasketItem.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgCasketItem proto.InternalMessageInfo

func (m *CMsgCasketItem) GetCasketItemId() uint64 {
	if m != nil && m.CasketItemId != nil {
		return *m.CasketItemId
	}
	return 0
}

func (m *CMsgCasketItem) GetItemItemId() uint64 {
	if m != nil && m.ItemItemId != nil {
		return *m.ItemItemId
	}
	return 0
}

type CMsgGCUserTrackTimePlayedConsecutively struct {
	State                *uint32  `protobuf:"varint,1,opt,name=state" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgGCUserTrackTimePlayedConsecutively) Reset() {
	*m = CMsgGCUserTrackTimePlayedConsecutively{}
}
func (m *CMsgGCUserTrackTimePlayedConsecutively) String() string { return proto.CompactTextString(m) }
func (*CMsgGCUserTrackTimePlayedConsecutively) ProtoMessage()    {}
func (*CMsgGCUserTrackTimePlayedConsecutively) Descriptor() ([]byte, []int) {
	return fileDescriptor_123d8ffb2ecfd02d, []int{3}
}

func (m *CMsgGCUserTrackTimePlayedConsecutively) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgGCUserTrackTimePlayedConsecutively.Unmarshal(m, b)
}
func (m *CMsgGCUserTrackTimePlayedConsecutively) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgGCUserTrackTimePlayedConsecutively.Marshal(b, m, deterministic)
}
func (m *CMsgGCUserTrackTimePlayedConsecutively) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgGCUserTrackTimePlayedConsecutively.Merge(m, src)
}
func (m *CMsgGCUserTrackTimePlayedConsecutively) XXX_Size() int {
	return xxx_messageInfo_CMsgGCUserTrackTimePlayedConsecutively.Size(m)
}
func (m *CMsgGCUserTrackTimePlayedConsecutively) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgGCUserTrackTimePlayedConsecutively.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgGCUserTrackTimePlayedConsecutively proto.InternalMessageInfo

func (m *CMsgGCUserTrackTimePlayedConsecutively) GetState() uint32 {
	if m != nil && m.State != nil {
		return *m.State
	}
	return 0
}

type CMsgGCItemCustomizationNotification struct {
	ItemId               []uint64 `protobuf:"varint,1,rep,name=item_id,json=itemId" json:"item_id,omitempty"`
	Request              *uint32  `protobuf:"varint,2,opt,name=request" json:"request,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgGCItemCustomizationNotification) Reset()         { *m = CMsgGCItemCustomizationNotification{} }
func (m *CMsgGCItemCustomizationNotification) String() string { return proto.CompactTextString(m) }
func (*CMsgGCItemCustomizationNotification) ProtoMessage()    {}
func (*CMsgGCItemCustomizationNotification) Descriptor() ([]byte, []int) {
	return fileDescriptor_123d8ffb2ecfd02d, []int{4}
}

func (m *CMsgGCItemCustomizationNotification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgGCItemCustomizationNotification.Unmarshal(m, b)
}
func (m *CMsgGCItemCustomizationNotification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgGCItemCustomizationNotification.Marshal(b, m, deterministic)
}
func (m *CMsgGCItemCustomizationNotification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgGCItemCustomizationNotification.Merge(m, src)
}
func (m *CMsgGCItemCustomizationNotification) XXX_Size() int {
	return xxx_messageInfo_CMsgGCItemCustomizationNotification.Size(m)
}
func (m *CMsgGCItemCustomizationNotification) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgGCItemCustomizationNotification.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgGCItemCustomizationNotification proto.InternalMessageInfo

func (m *CMsgGCItemCustomizationNotification) GetItemId() []uint64 {
	if m != nil {
		return m.ItemId
	}
	return nil
}

func (m *CMsgGCItemCustomizationNotification) GetRequest() uint32 {
	if m != nil && m.Request != nil {
		return *m.Request
	}
	return 0
}

func init() {
	proto.RegisterEnum("EGCItemMsg", EGCItemMsg_name, EGCItemMsg_value)
	proto.RegisterEnum("EGCMsgResponse", EGCMsgResponse_name, EGCMsgResponse_value)
	proto.RegisterEnum("EUnlockStyle", EUnlockStyle_name, EUnlockStyle_value)
	proto.RegisterEnum("EGCItemCustomizationNotification", EGCItemCustomizationNotification_name, EGCItemCustomizationNotification_value)
	proto.RegisterType((*CMsgGCGiftedItems)(nil), "CMsgGCGiftedItems")
	proto.RegisterType((*CMsgApplyAutograph)(nil), "CMsgApplyAutograph")
	proto.RegisterType((*CMsgCasketItem)(nil), "CMsgCasketItem")
	proto.RegisterType((*CMsgGCUserTrackTimePlayedConsecutively)(nil), "CMsgGCUserTrackTimePlayedConsecutively")
	proto.RegisterType((*CMsgGCItemCustomizationNotification)(nil), "CMsgGCItemCustomizationNotification")
}

func init() { proto.RegisterFile("econ_gcmessages.proto", fileDescriptor_123d8ffb2ecfd02d) }

var fileDescriptor_123d8ffb2ecfd02d = []byte{
	// 2665 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x58, 0x69, 0x70, 0x23, 0xc5,
	0xd9, 0xc6, 0x7b, 0x20, 0xd1, 0x5e, 0xef, 0xf6, 0xb6, 0x58, 0x30, 0xcb, 0x65, 0xbc, 0xb0, 0xdf,
	0x62, 0xee, 0x8f, 0xef, 0xa3, 0xf8, 0x91, 0xa4, 0x4a, 0x96, 0xb5, 0x8a, 0x6b, 0xed, 0x5d, 0x23,
	0xc9, 0x2c, 0xff, 0x54, 0xed, 0x99, 0x57, 0x72, 0x47, 0xa3, 0x6e, 0x6d, 0x4f, 0x8f, 0x6c, 0xf3,
	0x8b, 0x24, 0x55, 0x21, 0xf7, 0x9d, 0x54, 0xa5, 0x12, 0x72, 0x43, 0x02, 0xb9, 0xc9, 0x7d, 0x07,
	0x02, 0xe4, 0x3e, 0x80, 0x90, 0x83, 0x23, 0x1c, 0xb9, 0x20, 0x27, 0x84, 0x2b, 0xe4, 0xae, 0xee,
	0xd1, 0x8c, 0xba, 0x65, 0x79, 0xd1, 0xfe, 0x93, 0xfa, 0x7d, 0xfa, 0xed, 0xe7, 0x3d, 0xfb, 0xed,
	0x41, 0xbb, 0xc0, 0x13, 0xbc, 0xd6, 0xf0, 0x5a, 0x10, 0x86, 0xb4, 0x01, 0xe1, 0x85, 0x6d, 0x29,
	0x94, 0xd8, 0x9d, 0x0b, 0x15, 0xd0, 0x96, 0xbb, 0x38, 0xf9, 0xf8, 0x08, 0xda, 0x59, 0x98, 0x0f,
	0x1b, 0xa5, 0x42, 0x89, 0xd5, 0x15, 0xf8, 0xb3, 0x0a, 0x5a, 0x21, 0x39, 0x0d, 0x9d, 0x40, 0x3d,
	0x4f, 0x44, 0x5c, 0x31, 0x7f, 0x7c, 0x64, 0x62, 0x64, 0xdf, 0x58, 0xb9, 0xb7, 0x40, 0x26, 0xd1,
	0xb6, 0x06, 0xab, 0x2b, 0x1f, 0xea, 0x8c, 0xfb, 0xb0, 0x3a, 0xbe, 0xc9, 0x00, 0x9c, 0x35, 0x72,
	0x3e, 0x22, 0x2d, 0xba, 0x5a, 0xd3, 0x6b, 0x61, 0xad, 0x2d, 0xc2, 0x90, 0x2d, 0x05, 0x30, 0xbe,
	0xd9, 0x20, 0x71, 0x8b, 0xae, 0xea, 0xd3, 0xc2, 0x85, 0xee, 0x3a, 0xb9, 0x0c, 0x9d, 0xcc, 0xa3,
	0x56, 0x0d, 0x02, 0xd6, 0xd0, 0xff, 0x6b, 0x12, 0x3c, 0xd6, 0x66, 0xc0, 0x55, 0x38, 0xbe, 0xc5,
	0x6c, 0xd9, 0xc5, 0xa3, 0x56, 0xb1, 0x2b, 0x2d, 0xa7, 0x42, 0x72, 0x29, 0xda, 0xd5, 0x83, 0xd6,
	0x52, 0x86, 0xe1, 0xf8, 0xd6, 0x89, 0xcd, 0xfb, 0xc6, 0xca, 0x27, 0xf6, 0x84, 0xf9, 0x54, 0x36,
	0xb9, 0x84, 0x88, 0xb6, 0x38, 0xdf, 0x6e, 0x07, 0x6b, 0xf9, 0x48, 0x89, 0x86, 0xa4, 0xed, 0x65,
	0x32, 0x85, 0x76, 0xd2, 0xe4, 0x4f, 0x8d, 0x29, 0x68, 0xd5, 0xba, 0xa6, 0x6f, 0x29, 0xef, 0x48,
	0x05, 0xda, 0x3b, 0xb3, 0x3e, 0x99, 0x40, 0xdb, 0x62, 0x44, 0x17, 0xb6, 0xc9, 0xc0, 0x90, 0xfe,
	0x1b, 0x23, 0x26, 0xaf, 0x42, 0xdb, 0xf5, 0x19, 0x05, 0x1a, 0x36, 0x41, 0xe9, 0x35, 0x72, 0x36,
	0xda, 0xee, 0x99, 0x7f, 0x7d, 0xca, 0xb7, 0x79, 0x29, 0x66, 0x28, 0xcd, 0x2f, 0x42, 0x7b, 0xe3,
	0x78, 0x2d, 0x86, 0x20, 0xab, 0x92, 0x7a, 0xcd, 0x2a, 0x6b, 0xc1, 0x42, 0x40, 0xd7, 0xc0, 0x2f,
	0x08, 0x1e, 0x82, 0x17, 0x29, 0xd6, 0x81, 0x60, 0x8d, 0x9c, 0x88, 0xb6, 0x86, 0x8a, 0x2a, 0xe8,
	0x06, 0x30, 0xfe, 0x33, 0x79, 0x15, 0xda, 0x13, 0xef, 0xd7, 0xfa, 0x0a, 0x51, 0xa8, 0x44, 0x8b,
	0x5d, 0x4d, 0x15, 0x13, 0xfc, 0xa0, 0x50, 0xac, 0xce, 0x3c, 0xf3, 0x9b, 0x9c, 0x8c, 0x32, 0x3d,
	0x9e, 0x9b, 0xf7, 0x6d, 0x29, 0x1f, 0xcf, 0x62, 0x86, 0xe3, 0x28, 0x23, 0xe1, 0x48, 0x04, 0xa1,
	0xea, 0xc6, 0x3d, 0xf9, 0x3b, 0x75, 0xed, 0x3e, 0x84, 0x8a, 0xb1, 0xde, 0xf9, 0xb0, 0x41, 0x76,
	0xa2, 0x6d, 0xcd, 0x5a, 0xd1, 0x1c, 0x35, 0x4d, 0x43, 0xc0, 0x8f, 0x66, 0xc8, 0x69, 0xe8, 0xe4,
	0x64, 0xa9, 0x12, 0x9b, 0xbc, 0x20, 0x42, 0xa6, 0xcf, 0xc3, 0x8f, 0x65, 0x08, 0x41, 0x63, 0x89,
	0xb4, 0x20, 0x69, 0x5d, 0xe1, 0xdf, 0x67, 0xc8, 0x6e, 0xb4, 0xcb, 0x59, 0x2b, 0x43, 0xd8, 0xd6,
	0x46, 0xe2, 0x3f, 0x64, 0x48, 0x0e, 0x6d, 0x4f, 0x64, 0x33, 0x10, 0x80, 0x02, 0xfc, 0xc7, 0x0c,
	0x39, 0x1b, 0x9d, 0x99, 0x2c, 0x5e, 0x09, 0x92, 0xd5, 0xd7, 0x0a, 0xd4, 0x5b, 0x86, 0x4a, 0xb4,
	0x14, 0x7a, 0x92, 0xb5, 0xcd, 0x51, 0x7f, 0xca, 0x90, 0x5d, 0x08, 0x27, 0xa8, 0x83, 0xb4, 0x05,
	0x9a, 0x09, 0xfe, 0x73, 0x86, 0x8c, 0xa3, 0x5c, 0xb2, 0xbc, 0xc8, 0x03, 0xe1, 0x35, 0x0b, 0x92,
	0x2a, 0xc0, 0x7f, 0xc9, 0x90, 0x09, 0x74, 0xea, 0x00, 0x49, 0xca, 0xe6, 0xf1, 0x0c, 0x39, 0x09,
	0xed, 0x4c, 0x10, 0x0b, 0x94, 0x71, 0x63, 0x1d, 0x7e, 0x22, 0x43, 0xce, 0x40, 0xa7, 0xac, 0x5b,
	0x4f, 0xf7, 0xfd, 0x35, 0x43, 0x26, 0xd1, 0xe9, 0x89, 0xbc, 0x24, 0x02, 0x1f, 0xf8, 0x61, 0x09,
	0xdc, 0x5b, 0x9e, 0x96, 0x82, 0xfa, 0x1e, 0x0d, 0x15, 0x7e, 0xd2, 0xe1, 0x35, 0x7f, 0xa8, 0x3a,
	0x53, 0x8e, 0x1d, 0x8e, 0x9f, 0x72, 0x78, 0x59, 0x92, 0x54, 0xff, 0xd3, 0x19, 0xf2, 0x3f, 0x68,
	0x32, 0x41, 0xe4, 0x7d, 0x53, 0xde, 0x55, 0x51, 0x11, 0x9e, 0x4e, 0xc4, 0x99, 0xe2, 0x42, 0xb9,
	0x58, 0xc8, 0x57, 0x8b, 0x33, 0xf8, 0x99, 0x0c, 0xb9, 0x08, 0x4d, 0x6d, 0x00, 0x4c, 0xd4, 0xd9,
	0x1b, 0x9e, 0xcd, 0x90, 0xf3, 0xd0, 0x5e, 0x6b, 0x43, 0x0c, 0xad, 0x0a, 0x1d, 0x6b, 0xbd, 0xd9,
	0x06, 0xff, 0xad, 0x9f, 0x46, 0x02, 0xee, 0x07, 0x3e, 0xd7, 0x4f, 0xc3, 0x06, 0x0e, 0xa2, 0xf1,
	0xf7, 0x0c, 0x39, 0x05, 0x9d, 0x68, 0xc7, 0x32, 0x39, 0x1f, 0xff, 0x23, 0x43, 0xce, 0x42, 0xa7,
	0x0d, 0x12, 0xa5, 0xee, 0xf9, 0x67, 0x86, 0xec, 0x43, 0x7b, 0x12, 0x48, 0x19, 0x5a, 0xa2, 0x03,
	0xf1, 0x89, 0xfd, 0xc4, 0xfe, 0x95, 0x21, 0x17, 0xa3, 0xf3, 0x36, 0x42, 0x0e, 0x62, 0xf6, 0x6f,
	0xe7, 0xf8, 0xa4, 0xd0, 0xcc, 0xf9, 0x55, 0x58, 0x55, 0x91, 0x04, 0xfc, 0x9f, 0x0c, 0x39, 0x17,
	0x9d, 0x7d, 0x34, 0x48, 0xca, 0xf4, 0x9a, 0x2c, 0x39, 0x15, 0x9d, 0x94, 0xa6, 0x60, 0x62, 0x47,
	0x9c, 0x07, 0x2f, 0xcd, 0xda, 0x95, 0xb5, 0xd8, 0x67, 0xe4, 0xcb, 0xb2, 0x64, 0x0f, 0x3a, 0x23,
	0xcd, 0xb1, 0x5e, 0x97, 0xb7, 0xd9, 0xbe, 0xdc, 0xd1, 0x1f, 0xdb, 0xa7, 0x41, 0xda, 0x6d, 0xf8,
	0x15, 0x8e, 0xfe, 0x9e, 0xd0, 0xe4, 0x33, 0xbe, 0x36, 0x6b, 0x87, 0x40, 0xeb, 0x3f, 0x2c, 0x69,
	0xdb, 0x84, 0xe0, 0x95, 0x59, 0xdb, 0x07, 0xb6, 0x28, 0x65, 0xf7, 0xaa, 0xac, 0x9d, 0xdd, 0x33,
	0x10, 0xb0, 0x0e, 0x48, 0x8d, 0xc4, 0xaf, 0xce, 0x92, 0x73, 0xd0, 0xc4, 0x00, 0x49, 0xb2, 0xb7,
	0xa4, 0x17, 0xf0, 0x6b, 0xb2, 0x76, 0x0c, 0x07, 0xc0, 0xca, 0xe0, 0x81, 0x41, 0xbe, 0x36, 0x6b,
	0x17, 0xe3, 0x22, 0x5f, 0x91, 0xb4, 0x1d, 0x03, 0x63, 0x37, 0xbe, 0x2e, 0x4b, 0xce, 0x44, 0xbb,
	0x07, 0xc9, 0xbb, 0x5c, 0x5f, 0xef, 0x58, 0xda, 0xed, 0x60, 0x15, 0xb5, 0x16, 0x00, 0x7e, 0x83,
	0xab, 0x3b, 0x04, 0xbf, 0x10, 0x50, 0xd6, 0x2a, 0x08, 0x3f, 0x4e, 0xc6, 0x37, 0x66, 0xed, 0x06,
	0x51, 0x11, 0xd2, 0xec, 0x0d, 0xf1, 0x9b, 0xb2, 0x64, 0x0a, 0x9d, 0x93, 0xac, 0xd7, 0xca, 0xd0,
	0x11, 0x41, 0x87, 0xf1, 0xc6, 0x9c, 0x10, 0x6a, 0x8e, 0x85, 0x4e, 0x8d, 0xbe, 0x39, 0x6b, 0xb7,
	0xc3, 0x39, 0x21, 0x9a, 0x51, 0xbb, 0x7b, 0xad, 0xe1, 0xb7, 0x64, 0xed, 0x46, 0xe2, 0xc8, 0x52,
	0xfa, 0x6f, 0x75, 0x38, 0x3a, 0x18, 0x13, 0xe6, 0xb7, 0x65, 0xc9, 0x5e, 0x74, 0xd6, 0x86, 0xf2,
	0x54, 0xcf, 0xdb, 0xb3, 0xe4, 0x74, 0x34, 0x9e, 0xda, 0xda, 0xf6, 0xa9, 0x32, 0x46, 0x56, 0xbc,
	0x65, 0x68, 0x51, 0xfc, 0x8e, 0xac, 0xdd, 0x95, 0xe2, 0x6c, 0x89, 0x73, 0x3b, 0xc9, 0xfb, 0x77,
	0x66, 0xd7, 0x97, 0x9d, 0x83, 0x48, 0x8f, 0x7a, 0x97, 0x73, 0x54, 0x8c, 0x9c, 0xa7, 0x4d, 0x90,
	0xe1, 0x3c, 0x95, 0x4d, 0x7c, 0x9d, 0x93, 0x22, 0xfd, 0xe2, 0x54, 0xcb, 0xbb, 0x9d, 0x0a, 0x88,
	0x61, 0x8b, 0x9c, 0x1d, 0x89, 0xc0, 0xdc, 0x29, 0xb3, 0x7a, 0x60, 0xc1, 0xef, 0xc9, 0xda, 0x0d,
	0x6d, 0x30, 0x28, 0xd5, 0xf8, 0x5e, 0xa7, 0x5c, 0x2a, 0x74, 0x75, 0x75, 0xad, 0xd7, 0xb0, 0xdf,
	0xe7, 0x64, 0xfd, 0x34, 0xf5, 0x9a, 0x6d, 0xea, 0x35, 0x75, 0xcc, 0xf7, 0x33, 0xce, 0xc2, 0x65,
	0xf0, 0xf1, 0xfb, 0xb3, 0xf6, 0x45, 0x95, 0xf7, 0x5f, 0x12, 0x85, 0x26, 0x21, 0x8a, 0x47, 0x22,
	0xd6, 0x6e, 0x83, 0x5f, 0xd1, 0x57, 0x35, 0xfe, 0x80, 0x53, 0x1b, 0x05, 0x11, 0x04, 0xe0, 0xc5,
	0xf7, 0xca, 0xf5, 0x59, 0xbb, 0x73, 0xe8, 0xa5, 0xbc, 0xd7, 0xe4, 0x62, 0x25, 0x00, 0xbf, 0x01,
	0x7e, 0xcd, 0xce, 0x9a, 0x1b, 0x9c, 0xa4, 0xad, 0x95, 0xa1, 0x2d, 0xa4, 0xca, 0x2f, 0x45, 0x21,
	0xe0, 0x1b, 0x1d, 0xa2, 0xb6, 0x28, 0x35, 0xf4, 0xa6, 0x6c, 0x7f, 0x13, 0x35, 0x5d, 0xc1, 0x9a,
	0x14, 0xf0, 0x47, 0x1d, 0xef, 0x9a, 0xa9, 0x4a, 0xcf, 0x21, 0x51, 0x8b, 0x2e, 0x05, 0x50, 0xac,
	0xd7, 0xc1, 0x53, 0x21, 0xfe, 0x98, 0x93, 0x14, 0x96, 0x7c, 0x75, 0x99, 0x46, 0xa1, 0x02, 0x1f,
	0x7f, 0xdc, 0xc9, 0xce, 0xca, 0xb2, 0x58, 0x31, 0x15, 0xb2, 0xc0, 0xbc, 0x26, 0xf8, 0x8b, 0x6d,
	0xfc, 0x09, 0x27, 0x3b, 0x0b, 0x81, 0x9e, 0xea, 0x66, 0x58, 0xd8, 0x0e, 0xe8, 0x9a, 0x43, 0xe7,
	0x93, 0x4e, 0xca, 0x18, 0x3a, 0x15, 0x25, 0x29, 0x6f, 0xc0, 0x02, 0x95, 0x0a, 0x7f, 0xca, 0xf1,
	0x5c, 0x6d, 0x96, 0x7b, 0x12, 0x5a, 0xc0, 0xd5, 0x01, 0x16, 0x04, 0x05, 0x9d, 0xea, 0x79, 0xa5,
	0x24, 0x5b, 0x8a, 0x14, 0xe0, 0x9b, 0x9d, 0x34, 0x1d, 0x00, 0x4d, 0xbd, 0xf4, 0x69, 0xc7, 0x3a,
	0x73, 0xe6, 0x02, 0x70, 0x4e, 0xb9, 0x5a, 0x6c, 0x37, 0x24, 0xf5, 0x01, 0x7f, 0xc6, 0x61, 0xd5,
	0x37, 0xfc, 0x84, 0xf8, 0xb3, 0x4e, 0x87, 0x35, 0x0a, 0x8a, 0x8d, 0x46, 0x31, 0x0c, 0x81, 0x7b,
	0x80, 0x3f, 0xe7, 0x78, 0x58, 0x07, 0xa1, 0x27, 0x4c, 0x39, 0x7c, 0xde, 0x89, 0xb3, 0x69, 0xcd,
	0x07, 0x58, 0x9c, 0x2d, 0x5f, 0x70, 0x0e, 0x4f, 0x44, 0xe9, 0x45, 0xf9, 0x45, 0x27, 0xc6, 0xf6,
	0xce, 0x54, 0xf9, 0x97, 0x9c, 0x4c, 0xb4, 0xee, 0x10, 0xfc, 0x65, 0xf7, 0xee, 0x31, 0xb3, 0x51,
	0xaf, 0x2d, 0x7e, 0xc5, 0xc9, 0xf3, 0x3e, 0x69, 0xaa, 0xfd, 0xab, 0x0e, 0xf5, 0x6e, 0xc8, 0x74,
	0xdc, 0x25, 0xfe, 0x9a, 0x43, 0xbd, 0x3f, 0xd1, 0xf1, 0xd7, 0xdd, 0x8e, 0xac, 0xa8, 0xaa, 0x4a,
	0xda, 0xac, 0xac, 0xd0, 0x36, 0xfe, 0x46, 0x96, 0x5c, 0x80, 0xf6, 0x59, 0x1d, 0xf9, 0xa8, 0xc3,
	0x32, 0xbe, 0xc5, 0x69, 0xc4, 0x47, 0x9d, 0x8d, 0xf1, 0xad, 0x4e, 0xb8, 0xe7, 0x85, 0xcf, 0xea,
	0x6b, 0x86, 0x5a, 0x9a, 0x3a, 0xdf, 0x74, 0x5a, 0x75, 0xef, 0x15, 0x90, 0xf7, 0x7d, 0x7c, 0x9b,
	0x93, 0xe8, 0x3d, 0x59, 0x71, 0x55, 0x49, 0xea, 0x29, 0x7c, 0xbb, 0x13, 0xed, 0x9e, 0x7c, 0x4e,
	0x50, 0xcd, 0x59, 0xe9, 0xd7, 0x0c, 0xbe, 0xc3, 0x09, 0x48, 0x55, 0x52, 0x9f, 0xf1, 0x86, 0x19,
	0xb3, 0xef, 0x1f, 0xb5, 0x13, 0xbc, 0x2b, 0xa9, 0xcd, 0x72, 0xa6, 0x18, 0x55, 0xa0, 0xff, 0x43,
	0x72, 0xe1, 0x3d, 0x30, 0x6a, 0xdb, 0xbc, 0x01, 0xb4, 0x1b, 0xa3, 0x5f, 0x8e, 0xda, 0x49, 0x92,
	0x60, 0x2b, 0x8a, 0x4a, 0x55, 0x81, 0x30, 0xd4, 0x6e, 0x79, 0x70, 0xd4, 0x4e, 0x85, 0x14, 0x12,
	0xb3, 0xc7, 0x0f, 0x8d, 0xda, 0xb7, 0x6b, 0x22, 0xed, 0x0d, 0x13, 0xf8, 0xe1, 0x51, 0x3b, 0x57,
	0x12, 0x40, 0x7c, 0xbd, 0x18, 0x2e, 0xb3, 0xbc, 0x2e, 0xf0, 0x23, 0x83, 0x79, 0xe8, 0x21, 0x55,
	0xff, 0x84, 0x30, 0xc4, 0xbf, 0x1a, 0xb5, 0x3b, 0x45, 0xef, 0xa4, 0xae, 0x3c, 0x35, 0xe9, 0xd7,
	0xa3, 0xf6, 0x9d, 0xd9, 0x53, 0x65, 0xac, 0x29, 0x04, 0x22, 0x04, 0x1f, 0xff, 0x66, 0x20, 0xa6,
	0x40, 0xb9, 0x07, 0x41, 0x62, 0xf7, 0x6f, 0x07, 0x52, 0x32, 0x94, 0x0b, 0xcb, 0x54, 0xcd, 0x87,
	0x0d, 0xfc, 0xbb, 0x81, 0x90, 0x82, 0xe0, 0x75, 0x26, 0x5b, 0x87, 0xea, 0x75, 0x90, 0xf8, 0xd1,
	0x51, 0x7b, 0x46, 0x76, 0xb4, 0x54, 0xd7, 0xda, 0x8c, 0x37, 0x12, 0x5d, 0x8f, 0x39, 0x01, 0xae,
	0x80, 0xec, 0x80, 0x9c, 0x96, 0x62, 0x25, 0x04, 0x59, 0xdb, 0x4f, 0x3b, 0x42, 0x32, 0x05, 0xf1,
	0x2a, 0xbe, 0x65, 0x9b, 0x1d, 0x60, 0x17, 0x3a, 0x1d, 0x50, 0xaf, 0x19, 0xb0, 0x50, 0x75, 0xb1,
	0xb7, 0x6e, 0x73, 0xfa, 0xaf, 0x59, 0x2c, 0x03, 0x57, 0x34, 0x08, 0x4d, 0x5e, 0x7d, 0x70, 0xcc,
	0x4e, 0x4b, 0xd3, 0xbe, 0x24, 0x74, 0x18, 0xac, 0x14, 0x96, 0xc1, 0x6b, 0xea, 0xd2, 0x8b, 0x42,
	0x7c, 0xfd, 0x98, 0xed, 0x7a, 0x0b, 0x14, 0xcb, 0x53, 0xd7, 0xdf, 0x30, 0x66, 0x27, 0x83, 0x85,
	0x4b, 0x52, 0xf3, 0x43, 0x63, 0xb6, 0x37, 0xd6, 0x03, 0x52, 0x4d, 0x1f, 0x1e, 0xb3, 0x69, 0x5b,
	0xc0, 0xe2, 0x6a, 0x9b, 0x49, 0xc0, 0x37, 0x8e, 0xf5, 0xd7, 0xb5, 0x23, 0x77, 0xea, 0xfa, 0xa6,
	0x31, 0x72, 0x21, 0x3a, 0x77, 0x00, 0x56, 0xff, 0x9c, 0x16, 0x51, 0x63, 0x59, 0x39, 0xf8, 0x8f,
	0x38, 0x56, 0xcc, 0x40, 0xa7, 0x76, 0x30, 0xc6, 0x26, 0x56, 0xdc, 0xb9, 0xc3, 0xb6, 0x62, 0x3d,
	0x20, 0xb5, 0xe2, 0xae, 0x1d, 0x76, 0x7e, 0x68, 0x60, 0xd2, 0x86, 0x67, 0xa4, 0x88, 0x67, 0xe9,
	0xbb, 0x77, 0x38, 0x37, 0x88, 0x12, 0x12, 0x4a, 0xa0, 0x74, 0x5f, 0x9b, 0xa1, 0x8a, 0xe2, 0xdb,
	0x72, 0xf6, 0x28, 0xd4, 0x2f, 0x4e, 0x0f, 0xba, 0x3d, 0xe7, 0x24, 0x8f, 0x86, 0x2d, 0x44, 0xd2,
	0x5b, 0xd6, 0x77, 0x01, 0x67, 0xce, 0xb8, 0x79, 0x47, 0x8e, 0x5c, 0x82, 0xce, 0xdf, 0x10, 0x3a,
	0xe8, 0xcd, 0xf3, 0xad, 0x9c, 0x5d, 0x2d, 0xce, 0x96, 0xfd, 0x8c, 0xd3, 0x80, 0x5d, 0x0d, 0xf8,
	0xdb, 0x39, 0x27, 0x27, 0x07, 0x61, 0x52, 0xb6, 0xdf, 0xc9, 0xd9, 0x8d, 0xd6, 0xc1, 0xc6, 0x25,
	0x88, 0xbf, 0x9b, 0xb3, 0xef, 0xe8, 0x01, 0x88, 0x54, 0xd7, 0xf7, 0x36, 0xe6, 0x76, 0x45, 0x04,
	0x72, 0xad, 0xba, 0xca, 0xf1, 0xf7, 0x37, 0xe6, 0x96, 0x60, 0x52, 0x7d, 0x3f, 0xc8, 0x39, 0xf5,
	0xd2, 0xef, 0x1e, 0xfc, 0xc3, 0x9c, 0x5d, 0x0a, 0x1b, 0xba, 0x0f, 0xff, 0xc8, 0xe1, 0x35, 0x4d,
	0x39, 0x07, 0xff, 0xb0, 0x90, 0xbe, 0x9e, 0xfe, 0x93, 0x3c, 0xfa, 0x71, 0xce, 0xae, 0xbd, 0x7e,
	0x4c, 0x57, 0xd1, 0x9d, 0x8e, 0x2b, 0xaa, 0xa2, 0x1f, 0xd8, 0x1b, 0x50, 0xef, 0x72, 0xa8, 0xad,
	0x47, 0xc6, 0x3d, 0xd7, 0xc7, 0x77, 0x3b, 0x26, 0x6a, 0xdc, 0x0c, 0x93, 0x6a, 0xad, 0x32, 0x73,
	0xc8, 0x7c, 0x54, 0xc1, 0x3f, 0x59, 0xa7, 0xc7, 0xc8, 0xe7, 0xa3, 0x40, 0xb1, 0x76, 0x00, 0x29,
	0xee, 0x1e, 0xc7, 0x44, 0x8d, 0x8b, 0x4f, 0xa8, 0x5c, 0x31, 0x77, 0x00, 0xd6, 0xae, 0xa4, 0x41,
	0x04, 0xf8, 0xa7, 0x4e, 0xa8, 0x35, 0x66, 0x36, 0xac, 0x4a, 0x33, 0x1a, 0x76, 0x1b, 0xd4, 0xcf,
	0xd6, 0xd9, 0xd7, 0x87, 0x48, 0x3d, 0xf1, 0xf3, 0xf5, 0x9e, 0x48, 0x6c, 0xd7, 0x97, 0xbe, 0x08,
	0xa0, 0x20, 0x5a, 0x2d, 0xca, 0x7d, 0xfc, 0x8b, 0x9c, 0x5d, 0x77, 0xb1, 0x9a, 0x2b, 0x41, 0xea,
	0xb6, 0x9e, 0x38, 0xe1, 0xde, 0x9c, 0x3d, 0xea, 0xbb, 0x1f, 0x0d, 0xf1, 0x7d, 0x4e, 0xd5, 0xe9,
	0x93, 0x0e, 0xc3, 0x52, 0x7e, 0x61, 0xb6, 0xfb, 0x6c, 0x2a, 0x2c, 0xeb, 0xb9, 0xd3, 0xc7, 0xf7,
	0x3b, 0xc7, 0x74, 0xa3, 0x9a, 0xe7, 0x5c, 0x44, 0xdc, 0x33, 0x23, 0x65, 0x88, 0x1f, 0x70, 0x0a,
	0x73, 0x10, 0xa4, 0x77, 0x15, 0xe7, 0xdc, 0x57, 0x8f, 0x81, 0x2e, 0xd0, 0x30, 0x6c, 0x77, 0x9f,
	0x95, 0x25, 0x49, 0xb9, 0xc2, 0x0f, 0x3a, 0x87, 0xc6, 0x03, 0x73, 0x9f, 0x6d, 0x0f, 0x39, 0x87,
	0x6e, 0xf0, 0x0c, 0x31, 0xe1, 0xc4, 0x0f, 0xe7, 0xdc, 0x37, 0x9b, 0x17, 0x49, 0xc9, 0x78, 0xc3,
	0xfe, 0xb0, 0xd6, 0xbd, 0x03, 0x1e, 0xc9, 0x4d, 0xdd, 0xb3, 0x09, 0x6d, 0x2f, 0x96, 0x0a, 0xf3,
	0x61, 0x23, 0x21, 0x4d, 0x4e, 0x42, 0xa4, 0x59, 0x73, 0xd7, 0x0e, 0x1d, 0xc0, 0xc7, 0x91, 0xdd,
	0xc6, 0xb7, 0xce, 0xfa, 0x0c, 0x70, 0x06, 0x3e, 0x1e, 0x21, 0x67, 0x9a, 0x84, 0x70, 0x64, 0x71,
	0x88, 0x8a, 0x52, 0x0a, 0x89, 0x37, 0x91, 0x53, 0xcd, 0xb8, 0xe1, 0x00, 0xf4, 0x7c, 0x27, 0x22,
	0x85, 0x37, 0x0f, 0x12, 0xce, 0xf2, 0x0e, 0x0d, 0x98, 0x8f, 0xb7, 0x0c, 0x12, 0x1e, 0x14, 0xf3,
	0x54, 0x79, 0xcb, 0x78, 0x2b, 0x99, 0x30, 0x6e, 0x73, 0x84, 0x8b, 0x5c, 0x4f, 0x9d, 0x3c, 0x3e,
	0xf8, 0xf8, 0x41, 0xcc, 0x0e, 0x0a, 0x35, 0x27, 0x1a, 0x0d, 0xf0, 0x0f, 0x71, 0x9c, 0xb1, 0xcd,
	0xda, 0x4f, 0x59, 0x00, 0x7e, 0x55, 0x14, 0x24, 0xe8, 0x47, 0x9d, 0x9e, 0x58, 0x77, 0x25, 0xb2,
	0x39, 0xd6, 0x62, 0xaa, 0xb8, 0xea, 0x01, 0xf8, 0xe0, 0xe3, 0x13, 0xc8, 0xe9, 0xa6, 0xdc, 0x8c,
	0x48, 0xa7, 0x28, 0x53, 0x8b, 0xbc, 0xde, 0x6d, 0x8a, 0x3e, 0x46, 0x53, 0x8f, 0x8d, 0xa0, 0x6d,
	0xc5, 0x78, 0x8a, 0x36, 0x13, 0x74, 0x6c, 0x86, 0xb5, 0x50, 0xab, 0x44, 0x5e, 0x57, 0xd9, 0x71,
	0x31, 0x49, 0x5b, 0x18, 0x33, 0xa9, 0x2d, 0xe8, 0x07, 0xf6, 0x11, 0x3c, 0x42, 0xf6, 0xe8, 0x71,
	0x6b, 0x00, 0xa0, 0x40, 0xb9, 0xca, 0xd7, 0xeb, 0x42, 0xfa, 0x78, 0xd3, 0x51, 0x41, 0x31, 0x47,
	0xbc, 0x99, 0xec, 0xd5, 0xb7, 0xdc, 0x06, 0xa0, 0x39, 0xe1, 0x35, 0xe3, 0x3e, 0xb0, 0x85, 0x9c,
	0xab, 0xbb, 0xeb, 0x51, 0x4f, 0x8c, 0x67, 0x68, 0xbc, 0x75, 0xea, 0xe6, 0x13, 0xd0, 0x44, 0xf1,
	0xf9, 0xbe, 0x52, 0xc7, 0xdf, 0xe4, 0x9e, 0x07, 0x55, 0xb3, 0x3f, 0xf1, 0x5e, 0x8a, 0x2e, 0x1c,
	0x62, 0x47, 0xdf, 0xd7, 0xdf, 0xcb, 0xd0, 0x25, 0x43, 0x6c, 0xba, 0xaa, 0x4c, 0xd7, 0xe2, 0xcb,
	0xbd, 0x03, 0x34, 0xc0, 0x8f, 0x67, 0xc8, 0xff, 0xa3, 0x8b, 0x8f, 0x61, 0x9f, 0xf9, 0x62, 0x84,
	0x9f, 0x18, 0x76, 0x5b, 0xfc, 0x32, 0xa8, 0x0a, 0xb1, 0x3f, 0x0a, 0x02, 0xfc, 0xe4, 0xb0, 0x2c,
	0xe3, 0x6d, 0xe9, 0x43, 0xe2, 0xa9, 0x61, 0x5d, 0x12, 0xef, 0xcb, 0xfb, 0x3a, 0xb7, 0x9e, 0x3e,
	0x36, 0x8e, 0xf1, 0x90, 0xef, 0xe3, 0x67, 0x8e, 0x6d, 0xdb, 0x2c, 0xef, 0x18, 0xd3, 0x9e, 0xcd,
	0x90, 0xff, 0x43, 0x17, 0x0d, 0x19, 0x67, 0xfb, 0xf3, 0xef, 0x70, 0x0e, 0x59, 0xff, 0xb1, 0x73,
	0x38, 0x92, 0xdd, 0x8f, 0xc0, 0xdd, 0x87, 0xea, 0x75, 0xd9, 0x21, 0x49, 0xf6, 0x3f, 0x6f, 0x87,
	0xdb, 0xd5, 0xff, 0xb4, 0x1d, 0x2e, 0x66, 0x31, 0xc5, 0x05, 0xd3, 0xd6, 0x6e, 0xc9, 0x92, 0xff,
	0x45, 0x17, 0x0c, 0x4b, 0x30, 0xde, 0x73, 0x6b, 0x96, 0x5c, 0x8e, 0x2e, 0x1d, 0x66, 0x8f, 0xa7,
	0x58, 0x87, 0x2a, 0xd8, 0x4f, 0x79, 0x55, 0x34, 0x81, 0xe3, 0x7b, 0x4b, 0xe4, 0x85, 0xe8, 0xf2,
	0x63, 0xd8, 0x79, 0xa8, 0x0d, 0xd2, 0xac, 0x14, 0x04, 0xe3, 0xf8, 0xbe, 0xd2, 0x90, 0xc1, 0x2b,
	0x49, 0x5a, 0xaf, 0x33, 0xc5, 0x16, 0x79, 0xa8, 0x6b, 0xee, 0xe1, 0xd2, 0x90, 0x84, 0x4b, 0xc0,
	0xf5, 0x79, 0x50, 0x11, 0x51, 0x07, 0x38, 0x93, 0xf8, 0xa9, 0x12, 0xc9, 0xa3, 0x17, 0x0c, 0x93,
	0x9b, 0xe6, 0x22, 0x2d, 0x83, 0x0f, 0xd0, 0x9a, 0x67, 0xe6, 0x05, 0x58, 0x86, 0x15, 0x2a, 0x7d,
	0xfc, 0x5c, 0x69, 0x7a, 0xeb, 0x8b, 0x47, 0xae, 0x19, 0x39, 0xee, 0xbf, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xf8, 0x31, 0xb8, 0x6b, 0x81, 0x1d, 0x00, 0x00,
}
