// Code generated by protoc-gen-go. DO NOT EDIT.
// source: steammessages_credentials.steamclient.proto

package unified

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package unified is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package unified to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CCredentials_TestAvailablePassword_Request struct {
	Password             *string  `protobuf:"bytes,1,opt,name=password" json:"password,omitempty"`
	ShaDigestPassword    []byte   `protobuf:"bytes,2,opt,name=sha_digest_password,json=shaDigestPassword" json:"sha_digest_password,omitempty"`
	AccountName          *string  `protobuf:"bytes,3,opt,name=account_name,json=accountName" json:"account_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CCredentials_TestAvailablePassword_Request) Reset() {
	*m = CCredentials_TestAvailablePassword_Request{}
}
func (m *CCredentials_TestAvailablePassword_Request) String() string {
	return proto.CompactTextString(m)
}
func (*CCredentials_TestAvailablePassword_Request) ProtoMessage() {}
func (*CCredentials_TestAvailablePassword_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_50e19d183434a0ff, []int{0}
}

func (m *CCredentials_TestAvailablePassword_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CCredentials_TestAvailablePassword_Request.Unmarshal(m, b)
}
func (m *CCredentials_TestAvailablePassword_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CCredentials_TestAvailablePassword_Request.Marshal(b, m, deterministic)
}
func (m *CCredentials_TestAvailablePassword_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CCredentials_TestAvailablePassword_Request.Merge(m, src)
}
func (m *CCredentials_TestAvailablePassword_Request) XXX_Size() int {
	return xxx_messageInfo_CCredentials_TestAvailablePassword_Request.Size(m)
}
func (m *CCredentials_TestAvailablePassword_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_CCredentials_TestAvailablePassword_Request.DiscardUnknown(m)
}

var xxx_messageInfo_CCredentials_TestAvailablePassword_Request proto.InternalMessageInfo

func (m *CCredentials_TestAvailablePassword_Request) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *CCredentials_TestAvailablePassword_Request) GetShaDigestPassword() []byte {
	if m != nil {
		return m.ShaDigestPassword
	}
	return nil
}

func (m *CCredentials_TestAvailablePassword_Request) GetAccountName() string {
	if m != nil && m.AccountName != nil {
		return *m.AccountName
	}
	return ""
}

type CCredentials_TestAvailablePassword_Response struct {
	IsValid              *bool    `protobuf:"varint,3,opt,name=is_valid,json=isValid" json:"is_valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CCredentials_TestAvailablePassword_Response) Reset() {
	*m = CCredentials_TestAvailablePassword_Response{}
}
func (m *CCredentials_TestAvailablePassword_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CCredentials_TestAvailablePassword_Response) ProtoMessage() {}
func (*CCredentials_TestAvailablePassword_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_50e19d183434a0ff, []int{1}
}

func (m *CCredentials_TestAvailablePassword_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CCredentials_TestAvailablePassword_Response.Unmarshal(m, b)
}
func (m *CCredentials_TestAvailablePassword_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CCredentials_TestAvailablePassword_Response.Marshal(b, m, deterministic)
}
func (m *CCredentials_TestAvailablePassword_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CCredentials_TestAvailablePassword_Response.Merge(m, src)
}
func (m *CCredentials_TestAvailablePassword_Response) XXX_Size() int {
	return xxx_messageInfo_CCredentials_TestAvailablePassword_Response.Size(m)
}
func (m *CCredentials_TestAvailablePassword_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_CCredentials_TestAvailablePassword_Response.DiscardUnknown(m)
}

var xxx_messageInfo_CCredentials_TestAvailablePassword_Response proto.InternalMessageInfo

func (m *CCredentials_TestAvailablePassword_Response) GetIsValid() bool {
	if m != nil && m.IsValid != nil {
		return *m.IsValid
	}
	return false
}

type CCredentials_GetSteamGuardDetails_Request struct {
	IncludeNewAuthentications *bool    `protobuf:"varint,1,opt,name=include_new_authentications,json=includeNewAuthentications,def=1" json:"include_new_authentications,omitempty"`
	Webcookie                 *string  `protobuf:"bytes,2,opt,name=webcookie" json:"webcookie,omitempty"`
	TimestampMinimumWanted    *uint32  `protobuf:"fixed32,3,opt,name=timestamp_minimum_wanted,json=timestampMinimumWanted" json:"timestamp_minimum_wanted,omitempty"`
	Ipaddress                 *int32   `protobuf:"varint,4,opt,name=ipaddress" json:"ipaddress,omitempty"`
	XXX_NoUnkeyedLiteral      struct{} `json:"-"`
	XXX_unrecognized          []byte   `json:"-"`
	XXX_sizecache             int32    `json:"-"`
}

func (m *CCredentials_GetSteamGuardDetails_Request) Reset() {
	*m = CCredentials_GetSteamGuardDetails_Request{}
}
func (m *CCredentials_GetSteamGuardDetails_Request) String() string {
	return proto.CompactTextString(m)
}
func (*CCredentials_GetSteamGuardDetails_Request) ProtoMessage() {}
func (*CCredentials_GetSteamGuardDetails_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_50e19d183434a0ff, []int{2}
}

func (m *CCredentials_GetSteamGuardDetails_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CCredentials_GetSteamGuardDetails_Request.Unmarshal(m, b)
}
func (m *CCredentials_GetSteamGuardDetails_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CCredentials_GetSteamGuardDetails_Request.Marshal(b, m, deterministic)
}
func (m *CCredentials_GetSteamGuardDetails_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CCredentials_GetSteamGuardDetails_Request.Merge(m, src)
}
func (m *CCredentials_GetSteamGuardDetails_Request) XXX_Size() int {
	return xxx_messageInfo_CCredentials_GetSteamGuardDetails_Request.Size(m)
}
func (m *CCredentials_GetSteamGuardDetails_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_CCredentials_GetSteamGuardDetails_Request.DiscardUnknown(m)
}

var xxx_messageInfo_CCredentials_GetSteamGuardDetails_Request proto.InternalMessageInfo

const Default_CCredentials_GetSteamGuardDetails_Request_IncludeNewAuthentications bool = true

func (m *CCredentials_GetSteamGuardDetails_Request) GetIncludeNewAuthentications() bool {
	if m != nil && m.IncludeNewAuthentications != nil {
		return *m.IncludeNewAuthentications
	}
	return Default_CCredentials_GetSteamGuardDetails_Request_IncludeNewAuthentications
}

func (m *CCredentials_GetSteamGuardDetails_Request) GetWebcookie() string {
	if m != nil && m.Webcookie != nil {
		return *m.Webcookie
	}
	return ""
}

func (m *CCredentials_GetSteamGuardDetails_Request) GetTimestampMinimumWanted() uint32 {
	if m != nil && m.TimestampMinimumWanted != nil {
		return *m.TimestampMinimumWanted
	}
	return 0
}

func (m *CCredentials_GetSteamGuardDetails_Request) GetIpaddress() int32 {
	if m != nil && m.Ipaddress != nil {
		return *m.Ipaddress
	}
	return 0
}

type CCredentials_GetSteamGuardDetails_Response struct {
	IsSteamguardEnabled                                   *bool                                                           `protobuf:"varint,1,opt,name=is_steamguard_enabled,json=isSteamguardEnabled" json:"is_steamguard_enabled,omitempty"`
	TimestampSteamguardEnabled                            *uint32                                                         `protobuf:"fixed32,2,opt,name=timestamp_steamguard_enabled,json=timestampSteamguardEnabled" json:"timestamp_steamguard_enabled,omitempty"`
	DeprecatedNewauthentication                           []*CCredentials_GetSteamGuardDetails_Response_NewAuthentication `protobuf:"bytes,3,rep,name=deprecated_newauthentication,json=deprecatedNewauthentication" json:"deprecated_newauthentication,omitempty"`
	DeprecatedMachineNameUserchosen                       *string                                                         `protobuf:"bytes,4,opt,name=deprecated_machine_name_userchosen,json=deprecatedMachineNameUserchosen" json:"deprecated_machine_name_userchosen,omitempty"`
	DeprecatedTimestampMachineSteamguardEnabled           *uint32                                                         `protobuf:"fixed32,5,opt,name=deprecated_timestamp_machine_steamguard_enabled,json=deprecatedTimestampMachineSteamguardEnabled" json:"deprecated_timestamp_machine_steamguard_enabled,omitempty"`
	DeprecatedAuthenticationExistsFromGeolocBeforeMintime *bool                                                           `protobuf:"varint,6,opt,name=deprecated_authentication_exists_from_geoloc_before_mintime,json=deprecatedAuthenticationExistsFromGeolocBeforeMintime" json:"deprecated_authentication_exists_from_geoloc_before_mintime,omitempty"`
	DeprecatedMachineId                                   *uint64                                                         `protobuf:"varint,7,opt,name=deprecated_machine_id,json=deprecatedMachineId" json:"deprecated_machine_id,omitempty"`
	SessionData                                           []*CCredentials_GetSteamGuardDetails_Response_SessionData       `protobuf:"bytes,8,rep,name=session_data,json=sessionData" json:"session_data,omitempty"`
	IsTwofactorEnabled                                    *bool                                                           `protobuf:"varint,9,opt,name=is_twofactor_enabled,json=isTwofactorEnabled" json:"is_twofactor_enabled,omitempty"`
	TimestampTwofactorEnabled                             *uint32                                                         `protobuf:"fixed32,10,opt,name=timestamp_twofactor_enabled,json=timestampTwofactorEnabled" json:"timestamp_twofactor_enabled,omitempty"`
	IsPhoneVerified                                       *bool                                                           `protobuf:"varint,11,opt,name=is_phone_verified,json=isPhoneVerified" json:"is_phone_verified,omitempty"`
	XXX_NoUnkeyedLiteral                                  struct{}                                                        `json:"-"`
	XXX_unrecognized                                      []byte                                                          `json:"-"`
	XXX_sizecache                                         int32                                                           `json:"-"`
}

func (m *CCredentials_GetSteamGuardDetails_Response) Reset() {
	*m = CCredentials_GetSteamGuardDetails_Response{}
}
func (m *CCredentials_GetSteamGuardDetails_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CCredentials_GetSteamGuardDetails_Response) ProtoMessage() {}
func (*CCredentials_GetSteamGuardDetails_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_50e19d183434a0ff, []int{3}
}

func (m *CCredentials_GetSteamGuardDetails_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CCredentials_GetSteamGuardDetails_Response.Unmarshal(m, b)
}
func (m *CCredentials_GetSteamGuardDetails_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CCredentials_GetSteamGuardDetails_Response.Marshal(b, m, deterministic)
}
func (m *CCredentials_GetSteamGuardDetails_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CCredentials_GetSteamGuardDetails_Response.Merge(m, src)
}
func (m *CCredentials_GetSteamGuardDetails_Response) XXX_Size() int {
	return xxx_messageInfo_CCredentials_GetSteamGuardDetails_Response.Size(m)
}
func (m *CCredentials_GetSteamGuardDetails_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_CCredentials_GetSteamGuardDetails_Response.DiscardUnknown(m)
}

var xxx_messageInfo_CCredentials_GetSteamGuardDetails_Response proto.InternalMessageInfo

func (m *CCredentials_GetSteamGuardDetails_Response) GetIsSteamguardEnabled() bool {
	if m != nil && m.IsSteamguardEnabled != nil {
		return *m.IsSteamguardEnabled
	}
	return false
}

func (m *CCredentials_GetSteamGuardDetails_Response) GetTimestampSteamguardEnabled() uint32 {
	if m != nil && m.TimestampSteamguardEnabled != nil {
		return *m.TimestampSteamguardEnabled
	}
	return 0
}

func (m *CCredentials_GetSteamGuardDetails_Response) GetDeprecatedNewauthentication() []*CCredentials_GetSteamGuardDetails_Response_NewAuthentication {
	if m != nil {
		return m.DeprecatedNewauthentication
	}
	return nil
}

func (m *CCredentials_GetSteamGuardDetails_Response) GetDeprecatedMachineNameUserchosen() string {
	if m != nil && m.DeprecatedMachineNameUserchosen != nil {
		return *m.DeprecatedMachineNameUserchosen
	}
	return ""
}

func (m *CCredentials_GetSteamGuardDetails_Response) GetDeprecatedTimestampMachineSteamguardEnabled() uint32 {
	if m != nil && m.DeprecatedTimestampMachineSteamguardEnabled != nil {
		return *m.DeprecatedTimestampMachineSteamguardEnabled
	}
	return 0
}

func (m *CCredentials_GetSteamGuardDetails_Response) GetDeprecatedAuthenticationExistsFromGeolocBeforeMintime() bool {
	if m != nil && m.DeprecatedAuthenticationExistsFromGeolocBeforeMintime != nil {
		return *m.DeprecatedAuthenticationExistsFromGeolocBeforeMintime
	}
	return false
}

func (m *CCredentials_GetSteamGuardDetails_Response) GetDeprecatedMachineId() uint64 {
	if m != nil && m.DeprecatedMachineId != nil {
		return *m.DeprecatedMachineId
	}
	return 0
}

func (m *CCredentials_GetSteamGuardDetails_Response) GetSessionData() []*CCredentials_GetSteamGuardDetails_Response_SessionData {
	if m != nil {
		return m.SessionData
	}
	return nil
}

func (m *CCredentials_GetSteamGuardDetails_Response) GetIsTwofactorEnabled() bool {
	if m != nil && m.IsTwofactorEnabled != nil {
		return *m.IsTwofactorEnabled
	}
	return false
}

func (m *CCredentials_GetSteamGuardDetails_Response) GetTimestampTwofactorEnabled() uint32 {
	if m != nil && m.TimestampTwofactorEnabled != nil {
		return *m.TimestampTwofactorEnabled
	}
	return 0
}

func (m *CCredentials_GetSteamGuardDetails_Response) GetIsPhoneVerified() bool {
	if m != nil && m.IsPhoneVerified != nil {
		return *m.IsPhoneVerified
	}
	return false
}

type CCredentials_GetSteamGuardDetails_Response_NewAuthentication struct {
	TimestampSteamguardEnabled *uint32  `protobuf:"fixed32,1,opt,name=timestamp_steamguard_enabled,json=timestampSteamguardEnabled" json:"timestamp_steamguard_enabled,omitempty"`
	IsWebCookie                *bool    `protobuf:"varint,2,opt,name=is_web_cookie,json=isWebCookie" json:"is_web_cookie,omitempty"`
	Ipaddress                  *int32   `protobuf:"varint,3,opt,name=ipaddress" json:"ipaddress,omitempty"`
	GeolocInfo                 *string  `protobuf:"bytes,4,opt,name=geoloc_info,json=geolocInfo" json:"geoloc_info,omitempty"`
	IsRemembered               *bool    `protobuf:"varint,5,opt,name=is_remembered,json=isRemembered" json:"is_remembered,omitempty"`
	MachineNameUserSupplied    *string  `protobuf:"bytes,6,opt,name=machine_name_user_supplied,json=machineNameUserSupplied" json:"machine_name_user_supplied,omitempty"`
	Status                     *int32   `protobuf:"varint,7,opt,name=status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral       struct{} `json:"-"`
	XXX_unrecognized           []byte   `json:"-"`
	XXX_sizecache              int32    `json:"-"`
}

func (m *CCredentials_GetSteamGuardDetails_Response_NewAuthentication) Reset() {
	*m = CCredentials_GetSteamGuardDetails_Response_NewAuthentication{}
}
func (m *CCredentials_GetSteamGuardDetails_Response_NewAuthentication) String() string {
	return proto.CompactTextString(m)
}
func (*CCredentials_GetSteamGuardDetails_Response_NewAuthentication) ProtoMessage() {}
func (*CCredentials_GetSteamGuardDetails_Response_NewAuthentication) Descriptor() ([]byte, []int) {
	return fileDescriptor_50e19d183434a0ff, []int{3, 0}
}

func (m *CCredentials_GetSteamGuardDetails_Response_NewAuthentication) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CCredentials_GetSteamGuardDetails_Response_NewAuthentication.Unmarshal(m, b)
}
func (m *CCredentials_GetSteamGuardDetails_Response_NewAuthentication) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CCredentials_GetSteamGuardDetails_Response_NewAuthentication.Marshal(b, m, deterministic)
}
func (m *CCredentials_GetSteamGuardDetails_Response_NewAuthentication) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CCredentials_GetSteamGuardDetails_Response_NewAuthentication.Merge(m, src)
}
func (m *CCredentials_GetSteamGuardDetails_Response_NewAuthentication) XXX_Size() int {
	return xxx_messageInfo_CCredentials_GetSteamGuardDetails_Response_NewAuthentication.Size(m)
}
func (m *CCredentials_GetSteamGuardDetails_Response_NewAuthentication) XXX_DiscardUnknown() {
	xxx_messageInfo_CCredentials_GetSteamGuardDetails_Response_NewAuthentication.DiscardUnknown(m)
}

var xxx_messageInfo_CCredentials_GetSteamGuardDetails_Response_NewAuthentication proto.InternalMessageInfo

func (m *CCredentials_GetSteamGuardDetails_Response_NewAuthentication) GetTimestampSteamguardEnabled() uint32 {
	if m != nil && m.TimestampSteamguardEnabled != nil {
		return *m.TimestampSteamguardEnabled
	}
	return 0
}

func (m *CCredentials_GetSteamGuardDetails_Response_NewAuthentication) GetIsWebCookie() bool {
	if m != nil && m.IsWebCookie != nil {
		return *m.IsWebCookie
	}
	return false
}

func (m *CCredentials_GetSteamGuardDetails_Response_NewAuthentication) GetIpaddress() int32 {
	if m != nil && m.Ipaddress != nil {
		return *m.Ipaddress
	}
	return 0
}

func (m *CCredentials_GetSteamGuardDetails_Response_NewAuthentication) GetGeolocInfo() string {
	if m != nil && m.GeolocInfo != nil {
		return *m.GeolocInfo
	}
	return ""
}

func (m *CCredentials_GetSteamGuardDetails_Response_NewAuthentication) GetIsRemembered() bool {
	if m != nil && m.IsRemembered != nil {
		return *m.IsRemembered
	}
	return false
}

func (m *CCredentials_GetSteamGuardDetails_Response_NewAuthentication) GetMachineNameUserSupplied() string {
	if m != nil && m.MachineNameUserSupplied != nil {
		return *m.MachineNameUserSupplied
	}
	return ""
}

func (m *CCredentials_GetSteamGuardDetails_Response_NewAuthentication) GetStatus() int32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

type CCredentials_GetSteamGuardDetails_Response_SessionData struct {
	MachineId                                   *uint64                                                         `protobuf:"varint,1,opt,name=machine_id,json=machineId" json:"machine_id,omitempty"`
	MachineNameUserchosen                       *string                                                         `protobuf:"bytes,2,opt,name=machine_name_userchosen,json=machineNameUserchosen" json:"machine_name_userchosen,omitempty"`
	TimestampMachineSteamguardEnabled           *uint32                                                         `protobuf:"fixed32,3,opt,name=timestamp_machine_steamguard_enabled,json=timestampMachineSteamguardEnabled" json:"timestamp_machine_steamguard_enabled,omitempty"`
	AuthenticationExistsFromGeolocBeforeMintime *bool                                                           `protobuf:"varint,4,opt,name=authentication_exists_from_geoloc_before_mintime,json=authenticationExistsFromGeolocBeforeMintime" json:"authentication_exists_from_geoloc_before_mintime,omitempty"`
	Newauthentication                           []*CCredentials_GetSteamGuardDetails_Response_NewAuthentication `protobuf:"bytes,5,rep,name=newauthentication" json:"newauthentication,omitempty"`
	AuthenticationExistsFromSameIpBeforeMintime *bool                                                           `protobuf:"varint,6,opt,name=authentication_exists_from_same_ip_before_mintime,json=authenticationExistsFromSameIpBeforeMintime" json:"authentication_exists_from_same_ip_before_mintime,omitempty"`
	PublicIpv4                                  *uint32                                                         `protobuf:"varint,7,opt,name=public_ipv4,json=publicIpv4" json:"public_ipv4,omitempty"`
	PublicIpAddress                             *string                                                         `protobuf:"bytes,8,opt,name=public_ip_address,json=publicIpAddress" json:"public_ip_address,omitempty"`
	XXX_NoUnkeyedLiteral                        struct{}                                                        `json:"-"`
	XXX_unrecognized                            []byte                                                          `json:"-"`
	XXX_sizecache                               int32                                                           `json:"-"`
}

func (m *CCredentials_GetSteamGuardDetails_Response_SessionData) Reset() {
	*m = CCredentials_GetSteamGuardDetails_Response_SessionData{}
}
func (m *CCredentials_GetSteamGuardDetails_Response_SessionData) String() string {
	return proto.CompactTextString(m)
}
func (*CCredentials_GetSteamGuardDetails_Response_SessionData) ProtoMessage() {}
func (*CCredentials_GetSteamGuardDetails_Response_SessionData) Descriptor() ([]byte, []int) {
	return fileDescriptor_50e19d183434a0ff, []int{3, 1}
}

func (m *CCredentials_GetSteamGuardDetails_Response_SessionData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CCredentials_GetSteamGuardDetails_Response_SessionData.Unmarshal(m, b)
}
func (m *CCredentials_GetSteamGuardDetails_Response_SessionData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CCredentials_GetSteamGuardDetails_Response_SessionData.Marshal(b, m, deterministic)
}
func (m *CCredentials_GetSteamGuardDetails_Response_SessionData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CCredentials_GetSteamGuardDetails_Response_SessionData.Merge(m, src)
}
func (m *CCredentials_GetSteamGuardDetails_Response_SessionData) XXX_Size() int {
	return xxx_messageInfo_CCredentials_GetSteamGuardDetails_Response_SessionData.Size(m)
}
func (m *CCredentials_GetSteamGuardDetails_Response_SessionData) XXX_DiscardUnknown() {
	xxx_messageInfo_CCredentials_GetSteamGuardDetails_Response_SessionData.DiscardUnknown(m)
}

var xxx_messageInfo_CCredentials_GetSteamGuardDetails_Response_SessionData proto.InternalMessageInfo

func (m *CCredentials_GetSteamGuardDetails_Response_SessionData) GetMachineId() uint64 {
	if m != nil && m.MachineId != nil {
		return *m.MachineId
	}
	return 0
}

func (m *CCredentials_GetSteamGuardDetails_Response_SessionData) GetMachineNameUserchosen() string {
	if m != nil && m.MachineNameUserchosen != nil {
		return *m.MachineNameUserchosen
	}
	return ""
}

func (m *CCredentials_GetSteamGuardDetails_Response_SessionData) GetTimestampMachineSteamguardEnabled() uint32 {
	if m != nil && m.TimestampMachineSteamguardEnabled != nil {
		return *m.TimestampMachineSteamguardEnabled
	}
	return 0
}

func (m *CCredentials_GetSteamGuardDetails_Response_SessionData) GetAuthenticationExistsFromGeolocBeforeMintime() bool {
	if m != nil && m.AuthenticationExistsFromGeolocBeforeMintime != nil {
		return *m.AuthenticationExistsFromGeolocBeforeMintime
	}
	return false
}

func (m *CCredentials_GetSteamGuardDetails_Response_SessionData) GetNewauthentication() []*CCredentials_GetSteamGuardDetails_Response_NewAuthentication {
	if m != nil {
		return m.Newauthentication
	}
	return nil
}

func (m *CCredentials_GetSteamGuardDetails_Response_SessionData) GetAuthenticationExistsFromSameIpBeforeMintime() bool {
	if m != nil && m.AuthenticationExistsFromSameIpBeforeMintime != nil {
		return *m.AuthenticationExistsFromSameIpBeforeMintime
	}
	return false
}

func (m *CCredentials_GetSteamGuardDetails_Response_SessionData) GetPublicIpv4() uint32 {
	if m != nil && m.PublicIpv4 != nil {
		return *m.PublicIpv4
	}
	return 0
}

func (m *CCredentials_GetSteamGuardDetails_Response_SessionData) GetPublicIpAddress() string {
	if m != nil && m.PublicIpAddress != nil {
		return *m.PublicIpAddress
	}
	return ""
}

type CCredentials_NewMachineNotificationDialog_Request struct {
	IsApproved           *bool    `protobuf:"varint,1,opt,name=is_approved,json=isApproved" json:"is_approved,omitempty"`
	IsWizardComplete     *bool    `protobuf:"varint,2,opt,name=is_wizard_complete,json=isWizardComplete" json:"is_wizard_complete,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CCredentials_NewMachineNotificationDialog_Request) Reset() {
	*m = CCredentials_NewMachineNotificationDialog_Request{}
}
func (m *CCredentials_NewMachineNotificationDialog_Request) String() string {
	return proto.CompactTextString(m)
}
func (*CCredentials_NewMachineNotificationDialog_Request) ProtoMessage() {}
func (*CCredentials_NewMachineNotificationDialog_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_50e19d183434a0ff, []int{4}
}

func (m *CCredentials_NewMachineNotificationDialog_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CCredentials_NewMachineNotificationDialog_Request.Unmarshal(m, b)
}
func (m *CCredentials_NewMachineNotificationDialog_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CCredentials_NewMachineNotificationDialog_Request.Marshal(b, m, deterministic)
}
func (m *CCredentials_NewMachineNotificationDialog_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CCredentials_NewMachineNotificationDialog_Request.Merge(m, src)
}
func (m *CCredentials_NewMachineNotificationDialog_Request) XXX_Size() int {
	return xxx_messageInfo_CCredentials_NewMachineNotificationDialog_Request.Size(m)
}
func (m *CCredentials_NewMachineNotificationDialog_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_CCredentials_NewMachineNotificationDialog_Request.DiscardUnknown(m)
}

var xxx_messageInfo_CCredentials_NewMachineNotificationDialog_Request proto.InternalMessageInfo

func (m *CCredentials_NewMachineNotificationDialog_Request) GetIsApproved() bool {
	if m != nil && m.IsApproved != nil {
		return *m.IsApproved
	}
	return false
}

func (m *CCredentials_NewMachineNotificationDialog_Request) GetIsWizardComplete() bool {
	if m != nil && m.IsWizardComplete != nil {
		return *m.IsWizardComplete
	}
	return false
}

type CCredentials_NewMachineNotificationDialog_Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CCredentials_NewMachineNotificationDialog_Response) Reset() {
	*m = CCredentials_NewMachineNotificationDialog_Response{}
}
func (m *CCredentials_NewMachineNotificationDialog_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CCredentials_NewMachineNotificationDialog_Response) ProtoMessage() {}
func (*CCredentials_NewMachineNotificationDialog_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_50e19d183434a0ff, []int{5}
}

func (m *CCredentials_NewMachineNotificationDialog_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CCredentials_NewMachineNotificationDialog_Response.Unmarshal(m, b)
}
func (m *CCredentials_NewMachineNotificationDialog_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CCredentials_NewMachineNotificationDialog_Response.Marshal(b, m, deterministic)
}
func (m *CCredentials_NewMachineNotificationDialog_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CCredentials_NewMachineNotificationDialog_Response.Merge(m, src)
}
func (m *CCredentials_NewMachineNotificationDialog_Response) XXX_Size() int {
	return xxx_messageInfo_CCredentials_NewMachineNotificationDialog_Response.Size(m)
}
func (m *CCredentials_NewMachineNotificationDialog_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_CCredentials_NewMachineNotificationDialog_Response.DiscardUnknown(m)
}

var xxx_messageInfo_CCredentials_NewMachineNotificationDialog_Response proto.InternalMessageInfo

type CCredentials_ValidateEmailAddress_Request struct {
	Stoken               *string  `protobuf:"bytes,1,opt,name=stoken" json:"stoken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CCredentials_ValidateEmailAddress_Request) Reset() {
	*m = CCredentials_ValidateEmailAddress_Request{}
}
func (m *CCredentials_ValidateEmailAddress_Request) String() string {
	return proto.CompactTextString(m)
}
func (*CCredentials_ValidateEmailAddress_Request) ProtoMessage() {}
func (*CCredentials_ValidateEmailAddress_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_50e19d183434a0ff, []int{6}
}

func (m *CCredentials_ValidateEmailAddress_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CCredentials_ValidateEmailAddress_Request.Unmarshal(m, b)
}
func (m *CCredentials_ValidateEmailAddress_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CCredentials_ValidateEmailAddress_Request.Marshal(b, m, deterministic)
}
func (m *CCredentials_ValidateEmailAddress_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CCredentials_ValidateEmailAddress_Request.Merge(m, src)
}
func (m *CCredentials_ValidateEmailAddress_Request) XXX_Size() int {
	return xxx_messageInfo_CCredentials_ValidateEmailAddress_Request.Size(m)
}
func (m *CCredentials_ValidateEmailAddress_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_CCredentials_ValidateEmailAddress_Request.DiscardUnknown(m)
}

var xxx_messageInfo_CCredentials_ValidateEmailAddress_Request proto.InternalMessageInfo

func (m *CCredentials_ValidateEmailAddress_Request) GetStoken() string {
	if m != nil && m.Stoken != nil {
		return *m.Stoken
	}
	return ""
}

type CCredentials_ValidateEmailAddress_Response struct {
	WasValidated         *bool    `protobuf:"varint,1,opt,name=was_validated,json=wasValidated" json:"was_validated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CCredentials_ValidateEmailAddress_Response) Reset() {
	*m = CCredentials_ValidateEmailAddress_Response{}
}
func (m *CCredentials_ValidateEmailAddress_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CCredentials_ValidateEmailAddress_Response) ProtoMessage() {}
func (*CCredentials_ValidateEmailAddress_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_50e19d183434a0ff, []int{7}
}

func (m *CCredentials_ValidateEmailAddress_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CCredentials_ValidateEmailAddress_Response.Unmarshal(m, b)
}
func (m *CCredentials_ValidateEmailAddress_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CCredentials_ValidateEmailAddress_Response.Marshal(b, m, deterministic)
}
func (m *CCredentials_ValidateEmailAddress_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CCredentials_ValidateEmailAddress_Response.Merge(m, src)
}
func (m *CCredentials_ValidateEmailAddress_Response) XXX_Size() int {
	return xxx_messageInfo_CCredentials_ValidateEmailAddress_Response.Size(m)
}
func (m *CCredentials_ValidateEmailAddress_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_CCredentials_ValidateEmailAddress_Response.DiscardUnknown(m)
}

var xxx_messageInfo_CCredentials_ValidateEmailAddress_Response proto.InternalMessageInfo

func (m *CCredentials_ValidateEmailAddress_Response) GetWasValidated() bool {
	if m != nil && m.WasValidated != nil {
		return *m.WasValidated
	}
	return false
}

type CCredentials_SteamGuardPhishingReport_Request struct {
	ParamString          *string  `protobuf:"bytes,1,opt,name=param_string,json=paramString" json:"param_string,omitempty"`
	IpaddressActual      *string  `protobuf:"bytes,2,opt,name=ipaddress_actual,json=ipaddressActual" json:"ipaddress_actual,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CCredentials_SteamGuardPhishingReport_Request) Reset() {
	*m = CCredentials_SteamGuardPhishingReport_Request{}
}
func (m *CCredentials_SteamGuardPhishingReport_Request) String() string {
	return proto.CompactTextString(m)
}
func (*CCredentials_SteamGuardPhishingReport_Request) ProtoMessage() {}
func (*CCredentials_SteamGuardPhishingReport_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_50e19d183434a0ff, []int{8}
}

func (m *CCredentials_SteamGuardPhishingReport_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CCredentials_SteamGuardPhishingReport_Request.Unmarshal(m, b)
}
func (m *CCredentials_SteamGuardPhishingReport_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CCredentials_SteamGuardPhishingReport_Request.Marshal(b, m, deterministic)
}
func (m *CCredentials_SteamGuardPhishingReport_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CCredentials_SteamGuardPhishingReport_Request.Merge(m, src)
}
func (m *CCredentials_SteamGuardPhishingReport_Request) XXX_Size() int {
	return xxx_messageInfo_CCredentials_SteamGuardPhishingReport_Request.Size(m)
}
func (m *CCredentials_SteamGuardPhishingReport_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_CCredentials_SteamGuardPhishingReport_Request.DiscardUnknown(m)
}

var xxx_messageInfo_CCredentials_SteamGuardPhishingReport_Request proto.InternalMessageInfo

func (m *CCredentials_SteamGuardPhishingReport_Request) GetParamString() string {
	if m != nil && m.ParamString != nil {
		return *m.ParamString
	}
	return ""
}

func (m *CCredentials_SteamGuardPhishingReport_Request) GetIpaddressActual() string {
	if m != nil && m.IpaddressActual != nil {
		return *m.IpaddressActual
	}
	return ""
}

type CCredentials_SteamGuardPhishingReport_Response struct {
	IpaddressLoginattempt   *string  `protobuf:"bytes,1,opt,name=ipaddress_loginattempt,json=ipaddressLoginattempt" json:"ipaddress_loginattempt,omitempty"`
	CountrynameLoginattempt *string  `protobuf:"bytes,2,opt,name=countryname_loginattempt,json=countrynameLoginattempt" json:"countryname_loginattempt,omitempty"`
	StatenameLoginattempt   *string  `protobuf:"bytes,3,opt,name=statename_loginattempt,json=statenameLoginattempt" json:"statename_loginattempt,omitempty"`
	CitynameLoginattempt    *string  `protobuf:"bytes,4,opt,name=cityname_loginattempt,json=citynameLoginattempt" json:"cityname_loginattempt,omitempty"`
	IpaddressActual         *string  `protobuf:"bytes,5,opt,name=ipaddress_actual,json=ipaddressActual" json:"ipaddress_actual,omitempty"`
	CountrynameActual       *string  `protobuf:"bytes,6,opt,name=countryname_actual,json=countrynameActual" json:"countryname_actual,omitempty"`
	StatenameActual         *string  `protobuf:"bytes,7,opt,name=statename_actual,json=statenameActual" json:"statename_actual,omitempty"`
	CitynameActual          *string  `protobuf:"bytes,8,opt,name=cityname_actual,json=citynameActual" json:"cityname_actual,omitempty"`
	SteamguardCode          *string  `protobuf:"bytes,9,opt,name=steamguard_code,json=steamguardCode" json:"steamguard_code,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *CCredentials_SteamGuardPhishingReport_Response) Reset() {
	*m = CCredentials_SteamGuardPhishingReport_Response{}
}
func (m *CCredentials_SteamGuardPhishingReport_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CCredentials_SteamGuardPhishingReport_Response) ProtoMessage() {}
func (*CCredentials_SteamGuardPhishingReport_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_50e19d183434a0ff, []int{9}
}

func (m *CCredentials_SteamGuardPhishingReport_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CCredentials_SteamGuardPhishingReport_Response.Unmarshal(m, b)
}
func (m *CCredentials_SteamGuardPhishingReport_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CCredentials_SteamGuardPhishingReport_Response.Marshal(b, m, deterministic)
}
func (m *CCredentials_SteamGuardPhishingReport_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CCredentials_SteamGuardPhishingReport_Response.Merge(m, src)
}
func (m *CCredentials_SteamGuardPhishingReport_Response) XXX_Size() int {
	return xxx_messageInfo_CCredentials_SteamGuardPhishingReport_Response.Size(m)
}
func (m *CCredentials_SteamGuardPhishingReport_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_CCredentials_SteamGuardPhishingReport_Response.DiscardUnknown(m)
}

var xxx_messageInfo_CCredentials_SteamGuardPhishingReport_Response proto.InternalMessageInfo

func (m *CCredentials_SteamGuardPhishingReport_Response) GetIpaddressLoginattempt() string {
	if m != nil && m.IpaddressLoginattempt != nil {
		return *m.IpaddressLoginattempt
	}
	return ""
}

func (m *CCredentials_SteamGuardPhishingReport_Response) GetCountrynameLoginattempt() string {
	if m != nil && m.CountrynameLoginattempt != nil {
		return *m.CountrynameLoginattempt
	}
	return ""
}

func (m *CCredentials_SteamGuardPhishingReport_Response) GetStatenameLoginattempt() string {
	if m != nil && m.StatenameLoginattempt != nil {
		return *m.StatenameLoginattempt
	}
	return ""
}

func (m *CCredentials_SteamGuardPhishingReport_Response) GetCitynameLoginattempt() string {
	if m != nil && m.CitynameLoginattempt != nil {
		return *m.CitynameLoginattempt
	}
	return ""
}

func (m *CCredentials_SteamGuardPhishingReport_Response) GetIpaddressActual() string {
	if m != nil && m.IpaddressActual != nil {
		return *m.IpaddressActual
	}
	return ""
}

func (m *CCredentials_SteamGuardPhishingReport_Response) GetCountrynameActual() string {
	if m != nil && m.CountrynameActual != nil {
		return *m.CountrynameActual
	}
	return ""
}

func (m *CCredentials_SteamGuardPhishingReport_Response) GetStatenameActual() string {
	if m != nil && m.StatenameActual != nil {
		return *m.StatenameActual
	}
	return ""
}

func (m *CCredentials_SteamGuardPhishingReport_Response) GetCitynameActual() string {
	if m != nil && m.CitynameActual != nil {
		return *m.CitynameActual
	}
	return ""
}

func (m *CCredentials_SteamGuardPhishingReport_Response) GetSteamguardCode() string {
	if m != nil && m.SteamguardCode != nil {
		return *m.SteamguardCode
	}
	return ""
}

type CCredentials_LastCredentialChangeTime_Request struct {
	UserChangesOnly      *bool    `protobuf:"varint,1,opt,name=user_changes_only,json=userChangesOnly" json:"user_changes_only,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CCredentials_LastCredentialChangeTime_Request) Reset() {
	*m = CCredentials_LastCredentialChangeTime_Request{}
}
func (m *CCredentials_LastCredentialChangeTime_Request) String() string {
	return proto.CompactTextString(m)
}
func (*CCredentials_LastCredentialChangeTime_Request) ProtoMessage() {}
func (*CCredentials_LastCredentialChangeTime_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_50e19d183434a0ff, []int{10}
}

func (m *CCredentials_LastCredentialChangeTime_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CCredentials_LastCredentialChangeTime_Request.Unmarshal(m, b)
}
func (m *CCredentials_LastCredentialChangeTime_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CCredentials_LastCredentialChangeTime_Request.Marshal(b, m, deterministic)
}
func (m *CCredentials_LastCredentialChangeTime_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CCredentials_LastCredentialChangeTime_Request.Merge(m, src)
}
func (m *CCredentials_LastCredentialChangeTime_Request) XXX_Size() int {
	return xxx_messageInfo_CCredentials_LastCredentialChangeTime_Request.Size(m)
}
func (m *CCredentials_LastCredentialChangeTime_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_CCredentials_LastCredentialChangeTime_Request.DiscardUnknown(m)
}

var xxx_messageInfo_CCredentials_LastCredentialChangeTime_Request proto.InternalMessageInfo

func (m *CCredentials_LastCredentialChangeTime_Request) GetUserChangesOnly() bool {
	if m != nil && m.UserChangesOnly != nil {
		return *m.UserChangesOnly
	}
	return false
}

type CCredentials_LastCredentialChangeTime_Response struct {
	TimestampLastPasswordChange *uint32  `protobuf:"fixed32,1,opt,name=timestamp_last_password_change,json=timestampLastPasswordChange" json:"timestamp_last_password_change,omitempty"`
	TimestampLastEmailChange    *uint32  `protobuf:"fixed32,2,opt,name=timestamp_last_email_change,json=timestampLastEmailChange" json:"timestamp_last_email_change,omitempty"`
	TimestampLastPasswordReset  *uint32  `protobuf:"fixed32,3,opt,name=timestamp_last_password_reset,json=timestampLastPasswordReset" json:"timestamp_last_password_reset,omitempty"`
	XXX_NoUnkeyedLiteral        struct{} `json:"-"`
	XXX_unrecognized            []byte   `json:"-"`
	XXX_sizecache               int32    `json:"-"`
}

func (m *CCredentials_LastCredentialChangeTime_Response) Reset() {
	*m = CCredentials_LastCredentialChangeTime_Response{}
}
func (m *CCredentials_LastCredentialChangeTime_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CCredentials_LastCredentialChangeTime_Response) ProtoMessage() {}
func (*CCredentials_LastCredentialChangeTime_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_50e19d183434a0ff, []int{11}
}

func (m *CCredentials_LastCredentialChangeTime_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CCredentials_LastCredentialChangeTime_Response.Unmarshal(m, b)
}
func (m *CCredentials_LastCredentialChangeTime_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CCredentials_LastCredentialChangeTime_Response.Marshal(b, m, deterministic)
}
func (m *CCredentials_LastCredentialChangeTime_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CCredentials_LastCredentialChangeTime_Response.Merge(m, src)
}
func (m *CCredentials_LastCredentialChangeTime_Response) XXX_Size() int {
	return xxx_messageInfo_CCredentials_LastCredentialChangeTime_Response.Size(m)
}
func (m *CCredentials_LastCredentialChangeTime_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_CCredentials_LastCredentialChangeTime_Response.DiscardUnknown(m)
}

var xxx_messageInfo_CCredentials_LastCredentialChangeTime_Response proto.InternalMessageInfo

func (m *CCredentials_LastCredentialChangeTime_Response) GetTimestampLastPasswordChange() uint32 {
	if m != nil && m.TimestampLastPasswordChange != nil {
		return *m.TimestampLastPasswordChange
	}
	return 0
}

func (m *CCredentials_LastCredentialChangeTime_Response) GetTimestampLastEmailChange() uint32 {
	if m != nil && m.TimestampLastEmailChange != nil {
		return *m.TimestampLastEmailChange
	}
	return 0
}

func (m *CCredentials_LastCredentialChangeTime_Response) GetTimestampLastPasswordReset() uint32 {
	if m != nil && m.TimestampLastPasswordReset != nil {
		return *m.TimestampLastPasswordReset
	}
	return 0
}

type CCredentials_GetAccountAuthSecret_Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CCredentials_GetAccountAuthSecret_Request) Reset() {
	*m = CCredentials_GetAccountAuthSecret_Request{}
}
func (m *CCredentials_GetAccountAuthSecret_Request) String() string {
	return proto.CompactTextString(m)
}
func (*CCredentials_GetAccountAuthSecret_Request) ProtoMessage() {}
func (*CCredentials_GetAccountAuthSecret_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_50e19d183434a0ff, []int{12}
}

func (m *CCredentials_GetAccountAuthSecret_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CCredentials_GetAccountAuthSecret_Request.Unmarshal(m, b)
}
func (m *CCredentials_GetAccountAuthSecret_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CCredentials_GetAccountAuthSecret_Request.Marshal(b, m, deterministic)
}
func (m *CCredentials_GetAccountAuthSecret_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CCredentials_GetAccountAuthSecret_Request.Merge(m, src)
}
func (m *CCredentials_GetAccountAuthSecret_Request) XXX_Size() int {
	return xxx_messageInfo_CCredentials_GetAccountAuthSecret_Request.Size(m)
}
func (m *CCredentials_GetAccountAuthSecret_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_CCredentials_GetAccountAuthSecret_Request.DiscardUnknown(m)
}

var xxx_messageInfo_CCredentials_GetAccountAuthSecret_Request proto.InternalMessageInfo

type CCredentials_GetAccountAuthSecret_Response struct {
	SecretId             *int32   `protobuf:"varint,1,opt,name=secret_id,json=secretId" json:"secret_id,omitempty"`
	Secret               []byte   `protobuf:"bytes,2,opt,name=secret" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CCredentials_GetAccountAuthSecret_Response) Reset() {
	*m = CCredentials_GetAccountAuthSecret_Response{}
}
func (m *CCredentials_GetAccountAuthSecret_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CCredentials_GetAccountAuthSecret_Response) ProtoMessage() {}
func (*CCredentials_GetAccountAuthSecret_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_50e19d183434a0ff, []int{13}
}

func (m *CCredentials_GetAccountAuthSecret_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CCredentials_GetAccountAuthSecret_Response.Unmarshal(m, b)
}
func (m *CCredentials_GetAccountAuthSecret_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CCredentials_GetAccountAuthSecret_Response.Marshal(b, m, deterministic)
}
func (m *CCredentials_GetAccountAuthSecret_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CCredentials_GetAccountAuthSecret_Response.Merge(m, src)
}
func (m *CCredentials_GetAccountAuthSecret_Response) XXX_Size() int {
	return xxx_messageInfo_CCredentials_GetAccountAuthSecret_Response.Size(m)
}
func (m *CCredentials_GetAccountAuthSecret_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_CCredentials_GetAccountAuthSecret_Response.DiscardUnknown(m)
}

var xxx_messageInfo_CCredentials_GetAccountAuthSecret_Response proto.InternalMessageInfo

func (m *CCredentials_GetAccountAuthSecret_Response) GetSecretId() int32 {
	if m != nil && m.SecretId != nil {
		return *m.SecretId
	}
	return 0
}

func (m *CCredentials_GetAccountAuthSecret_Response) GetSecret() []byte {
	if m != nil {
		return m.Secret
	}
	return nil
}

func init() {
	proto.RegisterType((*CCredentials_TestAvailablePassword_Request)(nil), "CCredentials_TestAvailablePassword_Request")
	proto.RegisterType((*CCredentials_TestAvailablePassword_Response)(nil), "CCredentials_TestAvailablePassword_Response")
	proto.RegisterType((*CCredentials_GetSteamGuardDetails_Request)(nil), "CCredentials_GetSteamGuardDetails_Request")
	proto.RegisterType((*CCredentials_GetSteamGuardDetails_Response)(nil), "CCredentials_GetSteamGuardDetails_Response")
	proto.RegisterType((*CCredentials_GetSteamGuardDetails_Response_NewAuthentication)(nil), "CCredentials_GetSteamGuardDetails_Response.NewAuthentication")
	proto.RegisterType((*CCredentials_GetSteamGuardDetails_Response_SessionData)(nil), "CCredentials_GetSteamGuardDetails_Response.SessionData")
	proto.RegisterType((*CCredentials_NewMachineNotificationDialog_Request)(nil), "CCredentials_NewMachineNotificationDialog_Request")
	proto.RegisterType((*CCredentials_NewMachineNotificationDialog_Response)(nil), "CCredentials_NewMachineNotificationDialog_Response")
	proto.RegisterType((*CCredentials_ValidateEmailAddress_Request)(nil), "CCredentials_ValidateEmailAddress_Request")
	proto.RegisterType((*CCredentials_ValidateEmailAddress_Response)(nil), "CCredentials_ValidateEmailAddress_Response")
	proto.RegisterType((*CCredentials_SteamGuardPhishingReport_Request)(nil), "CCredentials_SteamGuardPhishingReport_Request")
	proto.RegisterType((*CCredentials_SteamGuardPhishingReport_Response)(nil), "CCredentials_SteamGuardPhishingReport_Response")
	proto.RegisterType((*CCredentials_LastCredentialChangeTime_Request)(nil), "CCredentials_LastCredentialChangeTime_Request")
	proto.RegisterType((*CCredentials_LastCredentialChangeTime_Response)(nil), "CCredentials_LastCredentialChangeTime_Response")
	proto.RegisterType((*CCredentials_GetAccountAuthSecret_Request)(nil), "CCredentials_GetAccountAuthSecret_Request")
	proto.RegisterType((*CCredentials_GetAccountAuthSecret_Response)(nil), "CCredentials_GetAccountAuthSecret_Response")
}

func init() {
	proto.RegisterFile("steammessages_credentials.steamclient.proto", fileDescriptor_50e19d183434a0ff)
}

var fileDescriptor_50e19d183434a0ff = []byte{
	// 1757 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0xcd, 0x6f, 0xdc, 0xc6,
	0x15, 0x07, 0x2d, 0xc9, 0xde, 0x7d, 0x2b, 0x47, 0xd6, 0xd8, 0x92, 0xe9, 0xb5, 0x13, 0xd1, 0x74,
	0x01, 0xc9, 0x96, 0xc3, 0x24, 0x8a, 0xdd, 0xaf, 0x20, 0x45, 0x65, 0xc9, 0x71, 0xd5, 0xc6, 0x8e,
	0x4b, 0xb9, 0x31, 0xd0, 0x1e, 0x88, 0x59, 0xf2, 0xed, 0xee, 0xc0, 0x24, 0x87, 0xe5, 0xcc, 0xee,
	0xd6, 0x01, 0x02, 0xa4, 0x7b, 0x6b, 0x0f, 0x45, 0xaf, 0x45, 0x7b, 0xe8, 0xa9, 0x7f, 0x40, 0x81,
	0x2d, 0xd0, 0x4b, 0xff, 0x9b, 0x1e, 0x7b, 0x6e, 0x8f, 0x05, 0x87, 0xb3, 0xe4, 0x7e, 0x70, 0x25,
	0x6d, 0xd1, 0x1b, 0xf9, 0xbe, 0xe6, 0x7d, 0xfc, 0xde, 0x7b, 0x33, 0xb0, 0x2f, 0x24, 0xd2, 0x28,
	0x42, 0x21, 0x68, 0x07, 0x85, 0xe7, 0xa7, 0x18, 0x60, 0x2c, 0x19, 0x0d, 0x85, 0xa3, 0x38, 0x7e,
	0xc8, 0x30, 0x96, 0x4e, 0x92, 0x72, 0xc9, 0x9b, 0x0f, 0xa7, 0x85, 0x7b, 0x31, 0x6b, 0x33, 0x0c,
	0xbc, 0x16, 0x15, 0x38, 0x2f, 0x6d, 0xff, 0xd1, 0x80, 0x07, 0x47, 0x47, 0xa5, 0x41, 0xef, 0x15,
	0x0a, 0x79, 0xd8, 0xa7, 0x2c, 0xa4, 0xad, 0x10, 0x5f, 0x52, 0x21, 0x06, 0x3c, 0x0d, 0x3c, 0x17,
	0x7f, 0xd9, 0x43, 0x21, 0x49, 0x13, 0x6a, 0x89, 0xa6, 0x99, 0x86, 0x65, 0xec, 0xd5, 0xdd, 0xe2,
	0x9f, 0x38, 0x70, 0x5d, 0x74, 0xa9, 0x17, 0xb0, 0x0e, 0x0a, 0xe9, 0x15, 0x62, 0x97, 0x2c, 0x63,
	0x6f, 0xdd, 0xdd, 0x14, 0x5d, 0x7a, 0xac, 0x38, 0x63, 0x9b, 0xe4, 0x2e, 0xac, 0x53, 0xdf, 0xe7,
	0xbd, 0x58, 0x7a, 0x31, 0x8d, 0xd0, 0x5c, 0x51, 0xf6, 0x1a, 0x9a, 0xf6, 0x82, 0x46, 0x68, 0xff,
	0x08, 0xf6, 0x2f, 0xe4, 0x9c, 0x48, 0x78, 0x2c, 0x90, 0xdc, 0x82, 0x1a, 0x13, 0x5e, 0x9f, 0x86,
	0x2c, 0x50, 0xd6, 0x6a, 0xee, 0x15, 0x26, 0xbe, 0xcc, 0x7e, 0xed, 0xbf, 0xaf, 0xc0, 0xfd, 0x29,
	0x53, 0xcf, 0x50, 0x9e, 0x66, 0xd9, 0x78, 0xd6, 0xa3, 0x69, 0x70, 0x8c, 0x92, 0xb2, 0x50, 0x14,
	0x61, 0xfe, 0xde, 0x80, 0xdb, 0x2c, 0xf6, 0xc3, 0x5e, 0x80, 0x5e, 0x8c, 0x03, 0x8f, 0xf6, 0x64,
	0x37, 0x53, 0xf4, 0xa9, 0x64, 0x3c, 0x16, 0x2a, 0xf4, 0xda, 0xf7, 0x57, 0x65, 0xda, 0xc3, 0x27,
	0x3f, 0x1e, 0x8e, 0xcc, 0xcf, 0x5e, 0x77, 0x51, 0x76, 0x31, 0xb5, 0x78, 0x6a, 0xc5, 0x5c, 0x5a,
	0x92, 0x5b, 0x09, 0x4f, 0x7a, 0x21, 0x95, 0x68, 0xc9, 0x2e, 0x5a, 0x31, 0x0e, 0xa6, 0x4d, 0x58,
	0x6d, 0x86, 0x61, 0x60, 0xb1, 0x58, 0xb1, 0x53, 0x1d, 0x80, 0x7b, 0x4b, 0x1f, 0xfa, 0x02, 0x07,
	0x87, 0xd3, 0x47, 0x92, 0x3f, 0x1b, 0x50, 0x1f, 0x60, 0xcb, 0xe7, 0xfc, 0x0d, 0x43, 0x95, 0xd4,
	0xfa, 0x93, 0x5f, 0x1b, 0xc3, 0x91, 0xf9, 0xf5, 0xab, 0x2e, 0x5a, 0x3d, 0x81, 0xe9, 0xae, 0xb0,
	0x54, 0x44, 0x96, 0x0a, 0xc9, 0x8a, 0xa8, 0xdf, 0x65, 0x31, 0x5a, 0xd9, 0xc1, 0x56, 0xae, 0xe6,
	0x58, 0x27, 0x6d, 0x2b, 0x49, 0x51, 0x60, 0x2c, 0x1f, 0x5a, 0x4c, 0xee, 0x86, 0xa1, 0xd5, 0x52,
	0xca, 0x41, 0xe6, 0x72, 0x07, 0xa5, 0x72, 0x47, 0x1b, 0x1b, 0x1b, 0x38, 0x39, 0xb6, 0x58, 0x9c,
	0x21, 0x27, 0xb0, 0x78, 0x5b, 0x09, 0x1c, 0x3e, 0xb7, 0x04, 0x0a, 0xc1, 0x78, 0xec, 0xb8, 0xa5,
	0x53, 0xe4, 0xbb, 0x60, 0x4a, 0x16, 0xa1, 0x90, 0x34, 0x4a, 0xbc, 0x88, 0xc5, 0x2c, 0xea, 0x45,
	0xde, 0x80, 0xc6, 0x12, 0xf3, 0x72, 0x5c, 0x71, 0xb7, 0x0b, 0xfe, 0xf3, 0x9c, 0xfd, 0x5a, 0x71,
	0xc9, 0x1d, 0xa8, 0xb3, 0x84, 0x06, 0x41, 0x8a, 0x42, 0x98, 0xab, 0x96, 0xb1, 0xb7, 0xe6, 0x96,
	0x04, 0xfb, 0x3f, 0x57, 0x67, 0x30, 0xba, 0xa0, 0x76, 0x1a, 0x05, 0x07, 0xb0, 0xc5, 0x84, 0xa7,
	0xa0, 0xde, 0xc9, 0x04, 0x3c, 0x8c, 0x33, 0xb8, 0xe4, 0x80, 0xad, 0xb9, 0xd7, 0x99, 0x38, 0x2d,
	0x78, 0x4f, 0x73, 0x16, 0xf9, 0x21, 0xdc, 0x29, 0x5d, 0xaf, 0x50, 0xbd, 0xa4, 0xdc, 0x6f, 0x16,
	0x32, 0xf3, 0x16, 0xbe, 0x31, 0xe0, 0x4e, 0x80, 0x49, 0x8a, 0x3e, 0x95, 0x18, 0x78, 0x73, 0x15,
	0x37, 0x57, 0xac, 0x95, 0xbd, 0xc6, 0xc1, 0xa7, 0xce, 0xc5, 0x23, 0x71, 0xe6, 0x60, 0xe0, 0xde,
	0x2e, 0x8f, 0x78, 0x31, 0x7b, 0x02, 0xf9, 0x09, 0xd8, 0x13, 0x1e, 0xe8, 0xf2, 0xa9, 0xde, 0xf2,
	0xb2, 0x92, 0xfa, 0x5d, 0x2e, 0x30, 0x56, 0xe9, 0xad, 0xbb, 0x3b, 0xa5, 0xe4, 0xf3, 0x5c, 0x30,
	0x6b, 0xb8, 0x9f, 0x15, 0x62, 0x24, 0x80, 0x0f, 0x26, 0x8c, 0x4d, 0xd4, 0x55, 0x9b, 0xad, 0x48,
	0xd2, 0x9a, 0x4a, 0xd2, 0x7e, 0xa9, 0xf6, 0xaa, 0xa8, 0x76, 0xae, 0x34, 0x9f, 0xb5, 0xaf, 0xe0,
	0x93, 0x89, 0x53, 0xa6, 0xe3, 0xf1, 0xf0, 0x57, 0x4c, 0x48, 0xe1, 0xb5, 0x53, 0x1e, 0x79, 0x1d,
	0xe4, 0x21, 0xf7, 0xbd, 0x16, 0xb6, 0x79, 0x8a, 0x19, 0xb8, 0x32, 0x8f, 0xcc, 0xcb, 0xaa, 0xa2,
	0x8f, 0x4b, 0x13, 0xd3, 0xe9, 0x7a, 0xaa, 0x0c, 0x7c, 0x96, 0xf2, 0xe8, 0x99, 0x52, 0x7f, 0xa2,
	0xb4, 0x9f, 0xe7, 0xca, 0x19, 0x4e, 0x2a, 0xd2, 0xc5, 0x02, 0xf3, 0x8a, 0x65, 0xec, 0xad, 0xba,
	0xd7, 0xe7, 0x32, 0x74, 0x12, 0x90, 0x9f, 0xc3, 0xba, 0x46, 0xbe, 0x17, 0x50, 0x49, 0xcd, 0x9a,
	0x2a, 0xea, 0x77, 0x96, 0x29, 0xea, 0x69, 0xae, 0x7f, 0x4c, 0x25, 0x75, 0x1b, 0xa2, 0xfc, 0x21,
	0x1f, 0xc2, 0x0d, 0x26, 0x3c, 0x39, 0xe0, 0x6d, 0xea, 0x4b, 0x9e, 0x16, 0x69, 0xad, 0xab, 0x20,
	0x09, 0x13, 0xaf, 0xc6, 0xac, 0x71, 0xf6, 0x7e, 0x00, 0xb7, 0xcb, 0xc2, 0xcc, 0x2b, 0x82, 0xaa,
	0xc7, 0xad, 0x42, 0x64, 0x4e, 0xff, 0x01, 0x6c, 0x32, 0xe1, 0x25, 0x5d, 0x1e, 0xa3, 0xd7, 0xc7,
	0x54, 0x2d, 0x0a, 0xb3, 0xa1, 0x8e, 0xdb, 0x60, 0xe2, 0x65, 0x46, 0xff, 0x52, 0x93, 0x9b, 0x7f,
	0xbd, 0x04, 0x9b, 0x73, 0x78, 0x3c, 0xb7, 0x6f, 0x8c, 0x73, 0xfb, 0xc6, 0x86, 0xab, 0x4c, 0x78,
	0x03, 0x6c, 0x79, 0x13, 0xa3, 0xad, 0xe6, 0x36, 0x98, 0x78, 0x8d, 0xad, 0xa3, 0x7c, 0xb0, 0x4c,
	0x8d, 0x87, 0x95, 0x99, 0xf1, 0x40, 0x76, 0xa0, 0xa1, 0xd1, 0xc1, 0xe2, 0x36, 0xd7, 0xf8, 0x86,
	0x9c, 0x74, 0x12, 0xb7, 0x39, 0xb9, 0xa7, 0x8e, 0x48, 0x31, 0xc2, 0xa8, 0x85, 0xa9, 0x06, 0x6a,
	0xcd, 0x5d, 0x67, 0xc2, 0x2d, 0x68, 0xe4, 0x13, 0x68, 0xce, 0x75, 0x8c, 0x27, 0x7a, 0x49, 0x12,
	0x66, 0x49, 0xb9, 0xac, 0x8c, 0xde, 0x8c, 0xa6, 0x5b, 0xe5, 0x54, 0xb3, 0xc9, 0x36, 0x5c, 0x16,
	0x92, 0xca, 0x9e, 0x50, 0xd8, 0x59, 0x73, 0xf5, 0x5f, 0xf3, 0x1f, 0xab, 0xd0, 0x98, 0xa8, 0x37,
	0x79, 0x17, 0x60, 0x02, 0x67, 0x86, 0xc2, 0x59, 0x3d, 0x2a, 0xd0, 0xf5, 0x6d, 0xb8, 0xb9, 0xa8,
	0x6b, 0xd5, 0xc0, 0x77, 0xb7, 0xa2, 0xca, 0x5e, 0xfd, 0x02, 0xbe, 0x75, 0xa1, 0x06, 0xcd, 0x87,
	0xf0, 0x5d, 0x79, 0x6e, 0x5b, 0x22, 0x7c, 0xb8, 0x74, 0x2f, 0xae, 0xaa, 0xa4, 0xee, 0xd3, 0x25,
	0x3a, 0xf0, 0x0d, 0x6c, 0xce, 0xcf, 0xc9, 0xb5, 0xff, 0xc7, 0x9c, 0x9c, 0xb7, 0x4b, 0xda, 0xf0,
	0xd1, 0x19, 0x31, 0x89, 0x2c, 0xdf, 0x2c, 0xa9, 0x1e, 0x30, 0x0b, 0x83, 0x3a, 0xa5, 0x11, 0x9e,
	0x24, 0xd3, 0x41, 0xed, 0x40, 0x23, 0xe9, 0xb5, 0x42, 0xe6, 0x7b, 0x2c, 0xe9, 0x3f, 0x52, 0x80,
	0xb8, 0xea, 0x42, 0x4e, 0x3a, 0x49, 0xfa, 0x8f, 0xb2, 0xae, 0x2b, 0x04, 0xbc, 0x31, 0xaa, 0x6b,
	0xaa, 0xbe, 0x1b, 0x63, 0xb1, 0x43, 0xbd, 0xfa, 0x86, 0x06, 0x7c, 0x34, 0x95, 0x88, 0x17, 0x38,
	0x18, 0xcf, 0x6b, 0x2e, 0x59, 0x5b, 0x7b, 0x74, 0xcc, 0x68, 0xc8, 0x3b, 0xc5, 0xf5, 0x65, 0x07,
	0x1a, 0x4c, 0x78, 0x34, 0x49, 0x52, 0xde, 0x2f, 0xf6, 0x1e, 0x30, 0x71, 0xa8, 0x29, 0xe4, 0x21,
	0x90, 0xac, 0xe9, 0xd8, 0x57, 0x19, 0x3a, 0x7c, 0x1e, 0x25, 0x21, 0xca, 0x71, 0xe7, 0x5d, 0x63,
	0xe2, 0xb5, 0x62, 0x1c, 0x69, 0xba, 0xfd, 0x08, 0x0e, 0x96, 0xf1, 0x21, 0x2f, 0x8a, 0x7d, 0x34,
	0x73, 0xe1, 0x52, 0xf7, 0x30, 0x2a, 0xf1, 0x69, 0x44, 0x59, 0xa8, 0xe3, 0x2b, 0x3c, 0x56, 0x0d,
	0xc4, 0xdf, 0x60, 0xac, 0x6f, 0x95, 0xfa, 0xcf, 0xfe, 0xe9, 0xcc, 0xe6, 0x5f, 0x60, 0x44, 0x6f,
	0xfe, 0x7b, 0x70, 0x75, 0x40, 0xf5, 0x05, 0x30, 0x9b, 0xdb, 0x3a, 0xf2, 0xf5, 0x01, 0x15, 0x63,
	0xc5, 0xc0, 0xfe, 0x1a, 0xde, 0x9f, 0x32, 0x59, 0xe2, 0xea, 0x65, 0x97, 0x89, 0x2e, 0x8b, 0x3b,
	0x2e, 0x26, 0x3c, 0x95, 0x85, 0x6f, 0x77, 0x61, 0x3d, 0xa1, 0x29, 0x8d, 0x3c, 0x21, 0x53, 0x16,
	0x77, 0xb4, 0x87, 0x0d, 0x45, 0x3b, 0x55, 0x24, 0x72, 0x1f, 0xae, 0x15, 0xf3, 0xc8, 0xa3, 0xbe,
	0xec, 0xd1, 0x50, 0x77, 0xec, 0x46, 0x41, 0x3f, 0x54, 0x64, 0xfb, 0x9f, 0x2b, 0xe0, 0x5c, 0xf4,
	0x7c, 0x1d, 0xd6, 0x63, 0xd8, 0x2e, 0xad, 0x87, 0xbc, 0xc3, 0x62, 0x2a, 0x25, 0x46, 0x89, 0xd4,
	0xae, 0x6c, 0x15, 0xdc, 0xcf, 0x27, 0x98, 0xe4, 0x7b, 0x60, 0xaa, 0x9b, 0x74, 0xfa, 0x56, 0x0d,
	0x93, 0x29, 0xc5, 0xdc, 0xb9, 0x9b, 0x13, 0xfc, 0x29, 0xd5, 0xc7, 0xb0, 0x9d, 0x4d, 0x30, 0x9c,
	0x57, 0xcc, 0x2f, 0xe9, 0x5b, 0x05, 0x77, 0x4a, 0xed, 0x63, 0xd8, 0xf2, 0x99, 0xac, 0x38, 0x2e,
	0x9f, 0xc9, 0x37, 0xc6, 0xcc, 0x29, 0xa5, 0xaa, 0xdc, 0xad, 0x55, 0xe6, 0x8e, 0xbc, 0x0f, 0x64,
	0x32, 0x22, 0x2d, 0x9c, 0xcf, 0xe6, 0xcd, 0x09, 0x8e, 0x16, 0xbf, 0x0f, 0xd7, 0xca, 0x28, 0xb4,
	0xf0, 0x95, 0xdc, 0x72, 0x41, 0xd7, 0xa2, 0xbb, 0xb0, 0x51, 0x78, 0xae, 0x25, 0xf3, 0x8e, 0x7c,
	0x67, 0x4c, 0x2e, 0x05, 0x27, 0x06, 0xab, 0xcf, 0x03, 0x54, 0xfb, 0xb9, 0xee, 0xbe, 0x53, 0x92,
	0x8f, 0x78, 0x80, 0xf6, 0x2f, 0x66, 0x60, 0xf6, 0x39, 0x15, 0xb2, 0xfc, 0x3f, 0xea, 0xd2, 0xb8,
	0x83, 0xd9, 0xfd, 0xa8, 0x80, 0xd9, 0x03, 0xd8, 0x54, 0x3b, 0xc7, 0x57, 0x2c, 0xe1, 0xf1, 0x38,
	0x7c, 0xab, 0x01, 0xbc, 0x91, 0x31, 0x72, 0x15, 0xf1, 0x45, 0x1c, 0xbe, 0xb5, 0xff, 0x6d, 0xcc,
	0x80, 0xe8, 0x0c, 0xeb, 0x1a, 0x44, 0x47, 0xf0, 0x5e, 0xb9, 0x23, 0x42, 0x3a, 0xf1, 0x42, 0xd3,
	0x27, 0xea, 0x5d, 0x5d, 0xde, 0x28, 0x32, 0x9b, 0xe3, 0x37, 0x56, 0x6e, 0x91, 0x7c, 0x3a, 0x79,
	0xe1, 0x50, 0x46, 0x30, 0x6b, 0xc4, 0xb1, 0x85, 0xfc, 0x96, 0x6c, 0x4e, 0x59, 0x50, 0x9d, 0xaa,
	0xd5, 0x0f, 0xe1, 0xdd, 0x45, 0x3e, 0x64, 0x8f, 0x12, 0xa9, 0x17, 0x54, 0xb3, 0xd2, 0x05, 0x37,
	0x93, 0xb0, 0xf7, 0xe7, 0x9f, 0x71, 0x87, 0xf9, 0x83, 0x31, 0xdb, 0x00, 0xa7, 0xe8, 0xa7, 0x58,
	0x74, 0xae, 0x4d, 0xe7, 0xdf, 0x0d, 0x55, 0xc2, 0x3a, 0x43, 0xb7, 0xa1, 0x2e, 0x72, 0x92, 0xde,
	0xcd, 0x6b, 0x6e, 0x2d, 0x27, 0x9c, 0xe4, 0x1b, 0x5e, 0x7d, 0xeb, 0xf7, 0xac, 0xfe, 0x3b, 0xf8,
	0x57, 0x0d, 0x1a, 0x13, 0x47, 0x90, 0xdf, 0x19, 0xb0, 0x55, 0xf9, 0x4a, 0x25, 0xfb, 0xce, 0xc5,
	0xdf, 0xd9, 0xcd, 0x87, 0xce, 0x12, 0xef, 0x5e, 0xbb, 0x39, 0x1c, 0x99, 0xdb, 0x95, 0x32, 0x0e,
	0xf9, 0xad, 0x01, 0x37, 0xaa, 0xb6, 0x27, 0x79, 0xe0, 0x5c, 0xf8, 0x3d, 0xdc, 0xdc, 0x5f, 0x62,
	0x1b, 0xdb, 0xb7, 0x86, 0x23, 0x73, 0xab, 0x4a, 0xc4, 0x21, 0x7f, 0x33, 0xc0, 0x3e, 0x6b, 0x7b,
	0xb8, 0x28, 0x7a, 0xa1, 0x24, 0x07, 0xce, 0xd2, 0x3b, 0xaf, 0xf9, 0xb1, 0xf3, 0x3f, 0xec, 0xa8,
	0xdd, 0xe1, 0xc8, 0xbc, 0x77, 0xbe, 0x43, 0x0e, 0xf9, 0x93, 0x01, 0x37, 0xaa, 0x76, 0xcf, 0x6c,
	0x16, 0xcf, 0x5a, 0x72, 0xb3, 0x59, 0x3c, 0x73, 0x97, 0xd9, 0xfb, 0xc3, 0x91, 0xb9, 0x3b, 0x16,
	0xb1, 0x68, 0x6c, 0xa9, 0x4e, 0xb3, 0xf4, 0x40, 0xb4, 0x3a, 0xac, 0x8f, 0xb1, 0x45, 0x2d, 0xb5,
	0x26, 0xc9, 0x1f, 0x0c, 0x30, 0x17, 0xed, 0x11, 0xe2, 0x38, 0x4b, 0xed, 0xbb, 0xe6, 0x07, 0x4b,
	0xee, 0x27, 0xfb, 0xce, 0x70, 0x64, 0x2e, 0x3e, 0xfe, 0x2f, 0x06, 0xbc, 0xf7, 0x0c, 0x2b, 0xa7,
	0xd3, 0x18, 0x8a, 0x8e, 0xb3, 0xd4, 0xa8, 0x9c, 0xf5, 0xf0, 0xdc, 0xe1, 0x67, 0xdf, 0x1b, 0x8e,
	0xcc, 0x9d, 0xb3, 0x9d, 0x70, 0xc8, 0x6f, 0xf2, 0x4e, 0x99, 0x9b, 0x10, 0x15, 0x9d, 0xb2, 0x70,
	0xe4, 0x54, 0x74, 0xca, 0xe2, 0x89, 0x63, 0x9b, 0xc3, 0x91, 0x59, 0x79, 0x64, 0xf3, 0xe6, 0x70,
	0x64, 0x5e, 0x9f, 0x30, 0x64, 0x09, 0x4c, 0xfb, 0xcc, 0xc7, 0x27, 0x2b, 0xdf, 0x18, 0xc6, 0x7f,
	0x03, 0x00, 0x00, 0xff, 0xff, 0x85, 0xf4, 0xc6, 0x9d, 0x10, 0x14, 0x00, 0x00,
}
